### ISSUE TITLE
5.0 docking via mouse cursor doesn't work

### ISSUE THREAD

**Issue by user-none** [user-none/KDocker#1]
In src/xlibutil.cpp line:
296     XWindowEvent(display, root, ButtonPressMask, &event);

It just gets stuck and nothing happens. Mouse button presses are never processed and processing (with docking) is never able to continue. Other masks such as keyboard masks don't make a difference either.

It is possible that this could be due to the fact that I'm running Linux in a VM on a Mac but I don't think that's the case. I'm using Ubuntu 14.04.

**Comment by Daxx** [comment]
$ ./kdocker -v
KDocker version: 5.0
Using Qt version: 5.2.1

$ ./kdocker    # (click on window - **docks OK**)

Fails using VirtualBox VM as yours does

**Comment by user-none** [comment]
@Daxx Are you saying that on real hardware (not though a vm) launching KDocker and clicking on a window is working. It's only when running though a VM that it's not working?

**Comment by Daxx** [comment]
Yes - on real Kubuntu 14.04 using your v5.0 - it works.

I just mentioned the VM to say that it's not just your VM that fails.

**Comment by user-none** [comment]
Hm... That's interesting. I'll need to see if 4.8 and 4.9 both work in a VM. That will tell me if it's an issue with VM's or Qt. I'd like to have it working in VM's but if it's not possible it's not possible...

**Comment by Daxx** [comment]
dave@dave-K64-15:/media/sf_KDocker$ ./kdocker -v
KDocker version: 4.8
Using Qt version: 4.8.6
dave@dave-K64-15:/media/sf_KDocker$ ./kdocker -tq
Select the application/window to dock with the left mouse button.
Click any other mouse button to abort.

Yes - works in my VM

**Comment by Daxx** [comment]
dave@dave-K64-15:/media/sf_KDocker$ ./kdocker -v
KDocker version: 4.9
Using Qt version: 4.8.6
dave@dave-K64-15:/media/sf_KDocker$ ./kdocker -tq
Select the application/window to dock with the left mouse button.
Click any other mouse button to abort.

Yes - 4.9 works on VM as well.

**Comment by Daxx** [comment]
This should be helpful ... it's **not** a VM problem!

I recreated my VM environment using a Real Live DVD run of
Kubuntu 15.04, in beta-testing, and the bug is there, also.

So, a more accurate report from me should have been:
- On real Kubuntu 14.04,  v5.0 works.
- On real (or VM) Kubuntu 15.04,  v5.0 doesn't work.

Completely different builds (Qt, X11 libs & whatever else).
```
$ ./kdocker -v        # on 14.04 (real)
KDocker version: 5.0
Using Qt version: 5.2.1       #  <------------|||
```
```
$ ./kdocker -v        # on 15.04 (real or VM)
KDocker version: 5.0
Using Qt version: 5.4.0       #  <------------|||   
```

So I think you can take back confidence in your VM.
Good luck squashing that sucker. :)

I don't think I've got the stamina to build 5.2.1 from git just to discover it's an X11 bug.
https://qt.gitorious.org/qt/qt5/source/811a77a53c9e5a05e01928f8efb6678e4637a4bf:README.git
https://qt.gitorious.org/qt/qt5/source/bf9c07353294d9c06516b0cc557c5cfe73867c83:

**Comment by user-none** [comment]
Basically this means I need to install and build against qt 5.4.0 and see if it's a Qt bug or an X11 bug. There have been multiple X11 bugs in the past that simply cannot be worked around. The only way to deal with them is wait for them to be fixed. This might be one of those situations. However, if 4.9 works then that's an indication it's a Qt bug.

**Comment by user-none** [comment]
4.8 with Qt4 works. So it's a Qt bug... Something in QtX11 is broken... I think it's not forwarding the events via the event filter properly.

**Comment by user-none** [comment]
http://doc.qt.io/qt-5/sourcebreaks.html
http://doc.qt.io/qt-5/qcoreapplication.html#installNativeEventFilter

Looks like Qt5 introduced a new way to handle X11 events. This whole part of KDocker is going to need to be rewritten for Qt5.

**Comment by Daxx** [comment]
Thanks, I was going to use an earlier g++ to check for compiler problems, so I can stop trashing my VM install, for now.

**Comment by user-none** [comment]
Yep the entire x11 handling needs to be rewritten using xcb. The event filter is gone and we probably need to use http://doc.qt.io/qt-5/qx11info.html#connectionx . Otherwise we can try the installNativeEventFilter and translate to QEvents but that won't really work when we're intercepting and manipulating events from other windows.

So basically Qt 5 messed up apps like Like KDocker over by moving strictly to xcb and away from xlib.

**Comment by Daxx** [comment]
Re: Title ... It does now :)
