### ISSUE TITLE
Let's implement different languages

### ISSUE THREAD

**Issue by andresgarcia0313** [user-none/KDocker#103]
Let's implement different languages

spanish pleas

**Comment by user-none** [comment]
Translations require one or more contributor to create the translations. Right now I don't want to incorporate machine translations.

**Comment by andresgarcia0313** [comment]
If you like I'll help you, Si gustas te ayudo

**Comment by user-none** [comment]
It's going to be a bit before translations can be worked on. The 6.0 update is making substantial enough changes it's going to have to wait until after that release and the strings in the app stabilize.
