### ISSUE TITLE
We can configure it to memorize the applications that should be in the system tray

### ISSUE THREAD

**Issue by andresgarcia0313** [user-none/KDocker#104]
We can configure it to memorize the applications that should be in the system tray?

**Comment by andresgarcia0313** [comment]
It would be great if the KDock software could memorize the applications that should be in the system tray. This enhancement would provide a more personalized and efficient experience for users. Thanks for considering it! 🌟

**Comment by user-none** [comment]
This isn't something that will be added. You can use a script to do this.
