### ISSUE TITLE
Was hoping we could maybe get a new release tag? now that the hang on reboot is resolved from pull request #100

### ISSUE THREAD

**Issue by Jieiku** [user-none/KDocker#107]
Was hoping we could maybe get a new release tag? now that the hang on reboot is resolved from pull request #100

https://github.com/user-none/KDocker/pull/100

My hope is that upstream repositories of various Linux distros will then bundle the newly fixed kdocker version tag.

**Comment by joanbm** [comment]
I'd also appreciate a release so #100 gets picked up by distros.

**Comment by ReaderGuy42** [comment]
> I'd also appreciate a release so #100 gets picked up by distros.

Stupid question, but how does this "get picked up by distros" work? Do you, the creators, have to upload it to the official repos?

**Comment by Jieiku** [comment]
well with Arch, packages generally get added to the AUR first then if popular enough they get added to the main repository: https://aur.archlinux.org/packages/kdocker

Once added automated build tools would grab the latest "release" from the source repository.

I am not sure at what point a package would get included with debian, but packages can start out as being available in a PPA, which can be similarly managed by the user instead of the distribution similar to the AUR. Kodi (xbmc) is for example available in the main debian repository, but on ubuntu it is still installed via a ppa: https://kodi.wiki/view/Official_Ubuntu_PPA

**Comment by ReaderGuy42** [comment]
Awesome, thanks for the info!!

**Comment by joanbm** [comment]
In the case of e.g. Debian, kdocker is already in the official repositories, but it's still at the latest released version (5.3), as usually distribution packagers just ship the latest released version. They include unreleased changes sometimes, but usually only if they are critical issues and/or they affect a big portion of the distribution's users.

**Comment by ReaderGuy42** [comment]
I'm on Linux Mint and it's in the official repo too, but it's on version 5.1 so I had to solve some dependencies to get 5.3 going.

**Comment by Jieiku** [comment]
If this gets seen by the Repository owner, feel free to add me as a maintainer if you want help with testing pull requests and issuing new releases.
