### ISSUE TITLE
Is there a command to show the docked application?

### ISSUE THREAD

**Issue by Stasky745** [user-none/KDocker#115]
I'm docking Thunderbird, but I want to have a shortcut to open it. I see that if I right click the docked icon there's the option "Show Thunderbird", but haven't seen how to do that from the command line. Is it possible?

**Comment by Daxx** [comment]
There's no shortcut in kdocker but windows are only "unmapped" (hidden) using standard functions.

So, try creating a global shortcut to execute this command:
`xdotool search --name ' - Mozilla Thunderbird$' windowmap windowactivate`

You might need to install `xdotool` from the repository.

### Custom Shortcut in KDE:
System Settings > Shortcuts > Custom Shortcuts > Edit > New > Global Shortcut > Command/URL.

**Comment by Daxx** [comment]
Getting more adventurous ...

You can toggle the current state by making a shortcut to this script:
**thun_toggle.sh** (or whatever)
```
#!/bin/bash

wid=$(xdotool search --name ' - Mozilla Thunderbird$' | head -1)
wstate=$(xwininfo -id $wid | grep "Map State:")

if [[ "$wstate" == *IsUnMapped ]]
then
  xdotool windowmap $wid windowactivate $wid
else
  xdotool windowunmap $wid
fi
```
In the "Trigger" tab, enter your hotkey (e.g. `WinKey + T` ... Appears as `Meta + T`).
In the "Action" tab, paste the path to the **executable** script (or use the file selector dialog button).

Apply.

TEST:
Press `Win T` -- Thunderbird appears
Press again -- it goes away
(continue until bored ... if ever) ;)

**Comment by Stasky745** [comment]
It doesn't seem to be working for me if I run Thunderbird with KDocker prior to using the command or script. I get

```
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
```

Works fine if I run Thunderbird by itself, but I'd like to know if it's running at any point and for that to have the icon docked with KDocker. Otherwise this is perfect.

**Comment by Stasky745** [comment]
It doesn't seem to be working for me if I run Thunderbird with KDocker prior to using the command or script. I get

```
XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
```

Works fine if I run Thunderbird by itself, but I'd like to know if it's running at any point and for that to have the icon docked with KDocker. Otherwise this is perfect.

**Comment by Daxx** [comment]
> 



> It doesn't seem to be working for me if I run Thunderbird with KDocker prior to using the command or script. I get
> 
> ```
> XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
> ```

Yes, I see that error when issuing the `xdotool` command from a console but it's an unrelated error.
Works, for me with Thunderbird docked under kdocker.

> 
> Works fine if I run Thunderbird by itself, but I'd like to know if it's running at any point and for that to have the icon docked with KDocker. Otherwise this is perfect.

You'll have to be more specific if you need further help from someone.

> I'd like to know if it's running at any point

You specified in your first post that it's already docked, so it's running (?)

> and for that to have the icon docked with KDocker.

???

Make sure your Thunderbird window title ends with " - Mozilla Thunderbird" because that's what is being searched for.
If not, change the `xdotool` search term, so that it matches what you can see.

If it's just your shortcut that doesn't work, find out how to do it on your O/S, whatever you're using.

I can't guarantee an answer better than the one I've given. It's not related to kdocker.

**Comment by user-none** [comment]
A DBus interface will be in v6.0 (future release) that supports this. You would need to use a DBus command line app to send the message.
