### ISSUE TITLE
kdocked windows vanish, without appearing in the system tray

### ISSUE THREAD

**Issue by junefish** [user-none/KDocker#116]
I'm not sure what logs or system info would be helpful here, but happy to provide whatever upon request.

When I launch Kdocker from the application menu, the cursor turns into the little square and then I click on the window I want to dock.  The window disappears and the application disappears from the dock, but nothing appears in the system tray.  (Other apps minimize fine to the system tray - Discord, Signal, ProtonVPN, etc).

If I run `kdocker $program` in the terminal, `$program` opens but then I get a KDocker popup that says <pre>Could not find a matching window for $program in the specified time: 5 seconds.</pre>

My laptop is running Pop_OS, Gnome desktop environment.

**Comment by Daxx** [comment]
Tried these on Pop!OS 22.04 in VirtualBox VM:
`kdocker gnome-calculator`  (docked OK, tray icon not very visible because dark)
`kdocker firefox`  (OK)

What $program did you try?

Did you try extending the wait time?:
`kdocker -d 10  $program`
