### ISSUE TITLE
clicking has no effect.

### ISSUE THREAD

**Issue by promeneur** [user-none/KDocker#117]
When launching kdocker, I get the kdocker mouse cursor, but clicking has no effect on any window.
The kdocker cursor never disappears. 
the action associated to the mouse cursor are disabled.
I must close the KDE session and reopen it.

Using kdocker in a script to launch an app works well.

Operating System: openSUSE Tumbleweed 20220930
KDE Gears 22.08.1
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6

Graphics Platform: X11 or Wayland

**Comment by simonbcn** [comment]
Same problem.

```
kdocker: 4.4
Operating System: Arch Linux
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 6.0.8-native_amd-xanmod1-1 (64-bit)
Graphics Platform: Wayland
Processors: 64 × AMD Ryzen Threadripper 3970X 32-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series
Manufacturer: ASUS
```

**Comment by FixitmanArizona** [comment]
Not Implemented in _Wayland_ yet as of July 2023. It works in _X11_ only according to the documentation.
Works fine in Xubuntu 22.04, which does not use Wayland using either _Status Tray_ plugin or _Indicator plugin_ (allowing it to show on a floating or alternate toolbar.)

**Comment by promeneur** [comment]
@FixitmanArizona 
I don't use wayland.

**Comment by promeneur** [comment]
Problem solved with X11.

**Comment by FixitmanArizona** [comment]
My comment was directed more at Wayland users who might read this thread, like simonbcn. I saw that your set-up included Wayland and/or x11.

**Comment by jahway603** [comment]
It would be nice to have Wayland support
