### ISSUE TITLE
(Double) Clicking on tray Icon doesn't show the application

### ISSUE THREAD

**Issue by lecovee** [user-none/KDocker#118]
When left clicking on a docked tray icon it shows me the context menu and when double clicking it shows the context menu and closes it again. It works when clicking the icon and then clicking on show application, but that is really inconvenient.

System info:
Ubuntu 22.04.1 LTS
GNOME 42.5
Windowing System X11

**Comment by furflez** [comment]
same here in ubuntu 22.04.1 LTS

**Comment by user-none** [comment]
This is a function of Gnome and not a bug.
