### ISSUE TITLE
Option do assign a shortcut for docked window

### ISSUE THREAD

**Issue by bodywithoutorgans** [user-none/KDocker#12]
It would be great to be able do assign keyboard shortcut for a docked window. Now we can do it in KDE window rules, but the shortcut is inactive once the window is hidden.

**Comment by Daxx** [comment]
I don't know what's wrong but that should work - and I think it does *start* to work.
However, KDocker docks it straight back before the window fully appears.
I've tested and seen a similar effect (using Firefox window as target) by opening 'System Activity', right-clicking on Firefox and 'Show Application Window'.  The window appeared, faintly, then went away.  (Often you see nothing.)
Similarly, if you have wmctrl package installed, this should also work (and *almost* does):
```shell
 wmctrl -a 'Mozilla Firefox' 
```
If anyone knows how it might be fixed, please comment.

**Comment by rapgro** [comment]
You would have to specify the shortcut with a cli option. KDocker instances a new process for every docked window. To avoid automatic re-docking, you can use some other cli options. See the existing options with kdocker -h.

**Comment by rosenfeld** [comment]
The lack of support of key bindings is what led me to create ktrayshortcut, but I don't have time to maintain it and could not find time to port it to KF5 yet. I'd love to see kdocker supporting global key bindings for toggling the windows...

**Comment by rosenfeld** [comment]
I realized I actually didn't miss support for tray icons, just global hotkeys to toggle the windows, so I created this application:

https://github.com/rosenfeld/hotkeys-manager

I'm posting here in case it fits the needs of other people looking at this issue...
