### ISSUE TITLE
Hide either original or KDocker icon in system tray?

### ISSUE THREAD

**Issue by dairefagan** [user-none/KDocker#120]
Ubuntu 22.04.1 LTS
Gnome 42.5
KDocker 5.3

I autostart Proton VPN with the command ```kdocker -t -d 15 -n Protonvpn protonvpn``` as there is no built-in minimise parameter. This results in 2 icons on my top panel:

![image](https://user-images.githubusercontent.com/12515718/215286588-808fb527-7ca9-4ade-ac14-bb9851fba15b.png)

Can you please tell me if it is possible to remove one of them? Preference to either keep the original or make the same click-menu options accessible from the KDocker icon.

**Comment by Rikj000** [comment]
I tried with `pidof` to get the process ID,   
and then `kdocker -x <process id>`,   
which sadly also leads to a double icon in the tray.

This of course only applies to programs which already have their own tray implementation    
(e.g. `virt-manager`, `fdm`, `yubico-authenticator`)

I hoped to use kdocker to automatically minimize these to the tray.

## Suggestion
Implement a new command flag to only "close" (minimize to tray) without starting a new kdocker tray entry.

**Comment by user-none** [comment]
> Implement a new command flag to only "close" (minimize to tray) without starting a new kdocker tray entry.

The purpose of KDocker is to dock applications to the system tray. It's a solution to hiding windows.  If they already have a tray icon then KDocke either isn't the right solution or you need to disable the application's tray icon if it allows that.
