### ISSUE TITLE
FluffyChat not being hidden from taskbar when `-t` option is specified

### ISSUE THREAD

**Issue by chriswyatt** [user-none/KDocker#123]
I dock FluffyChat as follows:
```shell
/usr/bin/kdocker -ot -i /usr/share/pixmaps/fluffychat.png /usr/bin/fluffychat
```

`-t` option seems to have no effect; FluffyChat still appears in taskbar when the window is visible. This possibly affects other Flutter apps too, but I haven't checked.

**Distribution**: Arch Linux
**FluffyChat package**: https://aur.archlinux.org/packages/fluffychat-bin
**FluffyChat package version**: 1.13.0-1
**Desktop environment**: LXQt
**Window manager**: Openbox

Workaround:
```xml
<!-- ~/.config/openbox/rc.xml -->
    <application name="fluffychat">
      <skip_taskbar>yes</skip_taskbar>
    </application>
```

**Comment by user-none** [comment]
KDocker send a message to the WM to not show in the task bar. If it's being ignored by the WM there isn't anything KDocker can do.
