### ISSUE TITLE
Don't dock when opening, but dock on minimize (split -m option into two)

### ISSUE THREAD

**Issue by Zorgodon** [user-none/KDocker#124]
The `-m` option seems to do two things at once: 
(1) Tells Kdocker to keep the program we just launched/ recognized via `-w $WID` open
(2) Disables the dock-on-minimize setting for that program

Is there any way to split this option into two? As in, I want the program to stay open, but still let me dock it when I click minimize. This setting is set in my `_GLOBAL_DEFAULTS` in kdocker.conf, but overridden by `-m`

I'll probably start poking the code to see if I can disable the function that does (2) when kdocker is run with `-m`, but I'm not too confident with C++ and QT, so any help would be very appreciated. @user-none

**Comment by user-none** [comment]
The logic when a window is docked has been questionable for a long time. It's on my todo list to look at while updating the code.

**Comment by user-none** [comment]
commit 7f7a0cc fixes the logic for what it's supposed to do but the request which is always iconify on first dock. I'm keeping this open since the request is for an option not to iconify on first dock.

**Comment by user-none** [comment]
Commit 47341d3 added the command line option `no-iconify-docking` and an new menu option for controlling iconifying when docking an application.
