### ISSUE TITLE
Not working with pavucontrol

### ISSUE THREAD

**Issue by iconoclasthero** [user-none/KDocker#125]
```
OS: Ubuntu 22.04.4 LTS x86_64 
DE: GNOME 42.9 
WM: Mutter 
pavucontrol: 5.0
$ kdocker -v
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QApplication: invalid style override 'Adwaita-Dark' passed, ignoring it.
	Available styles: Windows, Fusion
KDocker version: 5.3
Using Qt version: 5.15.3
```
I just installed kdocker specifically to knock pavucontrol down to the dock.  When I launch pavucontrol from the GUI the X cursor appears over chrome, not pavucontrol.  When I `$ kdocker pavucontrol` it launches pavucontrol in a "restored" window and then throws an error, `Could not find a matching window for pavucontrol in the specified time: 5 seconds.` The title for the pavucontrol window is " Volume Control" if it matters.

Again, this is the only thing I have ever wanted to do this for and it's less than fantastic that it isn't working...I assume that it's not going to because absolutely nothing to do with pulse/pipewire/mpd has been working for me lately so if that's the case, I'd rather know sooner rather than later.

**Comment by Daxx** [comment]
I'm on KDE and using `kdocker pavucontrol-qt` works for me. Should work on Gnome, also (?)

`sudo apt install pavucontrol-qt`

**Comment by Daxx** [comment]
Just tried the reverse, on KDE, for curiosity -- with no problems:

`sudo apt install pavucontrol`

`kdocker pavucontrol`

**Comment by iconoclasthero** [comment]
Hi, the pavucontrol-qt worked...
I don't imagine you're unbelieving that kdocker isn't working with `pavucontrol` for me, however i'll share this:

![Screenshot from 2024-04-03 11-54-23](https://github.com/user-none/KDocker/assets/535962/dd4de6f5-8ed5-49d5-96fc-d0c512e21cdd)

**Comment by Daxx** [comment]
Yes, I tried ```pavucontrol``` on Ubuntu 22.04 and got the same problem you reported.
I blame Wayland (which, apparently, is becoming more usable).

If you can close this issue #125, that would be great. Thanks.

**Comment by iconoclasthero** [comment]
closed: pavucontrol-qt proved workaround
