### ISSUE TITLE
Use application icon

### ISSUE THREAD

**Issue by Massimo-B** [user-none/KDocker#128]
kdocker-5.4, Linux

Please add an option to just use the application icon as kdocker icon in the tray. Currently I always need to set an icon for each application and save that setting.

**Comment by Daxx** [comment]
KDocker uses the application in the tray, if it can; that's normal.

Options -> Set icon
  followed by:
 Options -> Save settings -> {this_app} only
 is there in case you need to set it manually, the first time.


![Save_settings](https://github.com/user-attachments/assets/3e290f96-1533-44ca-bfb6-a25a71218616)

Good to see that you're using Linux for a Linux application. 
There's no KDocker option to fix all your problems with XFCE, sorry!

**Comment by Massimo-B** [comment]
I tried kdocker with edge browser, chrome browser, trying more applications like speedcrunch. kdocker always had a questionmark icon.
Trying more like galculator, gvim, it seems to work there.
Does KDocker try to lookup icons from /usr/share/icons? Can it just extract the icon from the application as the window manager also is able to show the icon in the task bar?

**Comment by Daxx** [comment]
> Does KDocker try to lookup icons from /usr/share/icons?

No, it uses [`XpmCreateDataFromPixmap`](https://man.archlinux.org/man/extra/libxpm/XpmCreateDataFromPixmap.3.en) to extract the icon from a window hint. If the hint is not maintained by the window manager (XFwm in your case), there'll be nothing there to extract, so KDocker resorts to the question mark.

https://github.com/user-none/KDocker/blob/82bea36f0afe464f4f2ea80b3a663f4cc741caa1/src/trayitem.cpp#L837

**Comment by Daxx** [comment]
Massimo,

It would be helpful if you could build from Misko's repo and provide some feedback.
Should be fine because I think he uses XFCE.

Things you might need:
`sudo apt install qt5-qmake  libqt5x11extras5-dev  libxcb1-dev  libx11-xcb-dev  libxmu-dev  libxpm-dev`

Thanks.

**Comment by Massimo-B** [comment]
As far as I see, @Misko-2083 's PR has already been merged and should solve the issue. Which kdocker release will include that? Last release 5.4 was in 2022.
