### ISSUE TITLE
Restore application on left click

### ISSUE THREAD

**Issue by jbd** [user-none/KDocker#13]
Hello,

I find (very subjective I admit) counter intuitive to open a contextual menu when left clicking the icon and then select "Show myapp" instead of having the application directly "restored". I don't know if it would be technically possible. 

What do you think ?

Jean-Baptiste

**Comment by Daxx** [comment]
This is similar to a question on the old tracker that John answered - https://answers.launchpad.net/kdocker/+question/209526.
I agree that the behaviour you describe would be counter-intuitive but that's not how it works on my system.  Single left-click toggles between show/hide window.  I don't understand why yours is different.

**Comment by jbd** [comment]
I'm running KDocker 4.6 from the debian stretch repository. I've just tried the master branch, same behaviour. I guess the problem should come from the Cinnamon system tray. I think you can close the issue for now.

Thank you for your answer !

**Comment by jbd** [comment]
Just for the record, this is related to : https://github.com/linuxmint/Cinnamon/issues/4946#issuecomment-165695685
