### ISSUE TITLE
Raise (undock) window on notification click

### ISSUE THREAD

**Issue by pabloh84** [user-none/KDocker#139]
**Problem:**

When notifications for docked applications (like Google Calendar or MS Teams PWA) are clicked, the applications remain docked instead of being raised to the forefront. This inconsistency with the behavior of minimized or obscured windows can be frustrating and inefficient.

**Solution:**

Implement a setting that allows for undock/raise of a window upon notification click. This would enable docked applications to be brought to the forefront when their notifications are clicked, mirroring the behavior of minimized or obscured windows.

**Example:**

- I have Google Calendar or MS Teams PWA opened and docked
- I receive an event (or chat) notification. The notification is shown in the OS tray normally. 
- I click the notification. 
  - **What I would expect**: The app is shown and raised (as it happens when it is just minimized or obscured)
  - **What actually happens**: The app keeps being docked and nothing happens (the notification is just discarded)

**Additional context**

I use kdocker 6.1 (though this has happened in all versions as far as I can remember) on Ubuntu 24.04 with GNOME over X11

**Comment by user-none** [comment]
Added in [97a6dce]. Note, not all desktops forward the event the same. See the table in the readme for which desktops this feature works with.

**Comment by pabloh84** [comment]
Hi @user-none 

Thanks for tackling this so fast. However I think this **does not solve the issue.**

I was referring to the notifications to app itself generates. **Don't know if it is even possible.**. I've made some videos to better illustrate my expectations.

- [Expected behavior - Window Minimized.webm](https://github.com/user-attachments/assets/303d7117-53c2-43f2-940d-0c9e9c87080c)
- [Wrong behavior - Window docked - App notification.webm](https://github.com/user-attachments/assets/1b951d65-df1c-4c87-9b82-cfccc0807c96)

Moreover, taking a look at your code it seems that you addressed this by adding a `toggleWindow` action to the notification KDocker generates on title change. I have compiled [https://github.com/user-none/KDocker/commit/97a6dce9bfa2e5df0cfec1b969bbaf4fdbc2991b] **and even that does not seem to work**, at least in my environment (Ubuntu 24.04 - Gnome 46 - KDocker compiled from latest)

- [Proposed solution - Wrong behavior - Name change notification does not rise the window.webm](https://github.com/user-attachments/assets/26cdb812-8209-4b9a-b87d-1f627fd2a100)

I've been fiddling around a bit and since you have moved to using DBus I would try to somehow monitor `org.freedesktop.Notifications` and try to show the window when clicked...

<pre><font color="#26A269"><b>pablo@pablo-prestige</b></font>:<font color="#12488B"><b>~</b></font>$ dbus-monitor &quot;interface=&apos;org.freedesktop.Notifications&apos;&quot;

##########################
# NOTIFICATION RECEPTION #
##########################

method call time=1727947386.996189 sender=:1.112 -&gt; destination=org.freedesktop.Notifications serial=48 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string &quot;Google Chrome&quot;
   uint32 0
   string &quot;file:///tmp/.com.google.Chrome.zIt8li&quot;
   string &quot;test&quot;
   string &quot;calendar.google.com

11:23 – 11:38&quot;
   array [
      string &quot;0&quot;
      string &quot;Snooze for 5 minutes&quot;
      string &quot;default&quot;
      string &quot;Activate&quot;
      string &quot;settings&quot;
      string &quot;Settings&quot;
   ]
   array [
      dict entry(
         string &quot;urgency&quot;
         variant             uint32 2
      )
      dict entry(
         string &quot;desktop-entry&quot;
         variant             string &quot;google-chrome&quot;
      )
      dict entry(
         string &quot;image_path&quot;
         variant             string &quot;/tmp/.com.google.Chrome.trEIVO&quot;
      )
      dict entry(
         string &quot;image-path&quot;
         variant             string &quot;/tmp/.com.google.Chrome.trEIVO&quot;
      )
   ]
   int32 0
method call time=1727947386.998324 sender=:1.50 -&gt; destination=:1.44 serial=395 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string &quot;Google Chrome&quot;
   uint32 0
   string &quot;file:///tmp/.com.google.Chrome.zIt8li&quot;
   string &quot;test&quot;
   string &quot;calendar.google.com

11:23 – 11:38&quot;
   array [
      string &quot;0&quot;
      string &quot;Snooze for 5 minutes&quot;
      string &quot;default&quot;
      string &quot;Activate&quot;
      string &quot;settings&quot;
      string &quot;Settings&quot;
   ]
   array [
      dict entry(
         string &quot;urgency&quot;
         variant             uint32 2
      )
      dict entry(
         string &quot;desktop-entry&quot;
         variant             string &quot;google-chrome&quot;
      )
      dict entry(
         string &quot;image_path&quot;
         variant             string &quot;/tmp/.com.google.Chrome.trEIVO&quot;
      )
      dict entry(
         string &quot;image-path&quot;
         variant             string &quot;/tmp/.com.google.Chrome.trEIVO&quot;
      )
      dict entry(
         string &quot;x-shell-sender-pid&quot;
         variant             uint32 4434
      )
      dict entry(
         string &quot;x-shell-sender&quot;
         variant             string &quot;:1.112&quot;
      )
   ]
   int32 0

##########################
# NOTIFICATION CLICKED   #
##########################

signal time=1727947394.730594 sender=:1.44 -&gt; destination=(null destination) serial=47785 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=ActivationToken
   uint32 49
   string &quot;gnome-shell/Google Calendar/2762-14-pablo-prestige_TIME14752426&quot;
signal time=1727947394.731186 sender=:1.44 -&gt; destination=(null destination) serial=47786 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=ActionInvoked
   uint32 49
   string &quot;default&quot;
signal time=1727947394.731845 sender=:1.44 -&gt; destination=(null destination) serial=47787 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 49
   uint32 2
signal time=1727947394.734102 sender=:1.50 -&gt; destination=:1.112 serial=397 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=ActivationToken
   uint32 49
   string &quot;gnome-shell/Google Calendar/2762-14-pablo-prestige_TIME14752426&quot;
signal time=1727947394.735019 sender=:1.50 -&gt; destination=:1.112 serial=398 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=ActionInvoked
   uint32 49
   string &quot;default&quot;
signal time=1727947394.735973 sender=:1.50 -&gt; destination=:1.112 serial=399 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 49
   uint32 2

</pre>
