### ISSUE TITLE
mouse scroll doesn't work

### ISSUE THREAD

**Issue by e-orz** [user-none/KDocker#14]
Hi,
I am on Ubuntu 16.04, Unity.
I compiled the code today and used the last development version.
kdocker -v:
KDocker version: 5.0
Using Qt version: 5.5.1

When scrolling the mouse over the icon, the application doesn't hide and show.
In the console window I get:
QMetaObject::invokeMethod: No such method AppMenuPlatformSystemTrayIcon::Scroll(int,QString)

Thanks!

**Comment by user-none** [comment]
This is an issue with Unity (http://bazaar.launchpad.net/~mitya57/appmenu-qt5/menus-and-systemtrayicons/revision/28). Basically, Unity stopped supporting how Qt5 puts things into the system try so they wrote library that translate how Qt5 does it to how Unity does. The wrappers doesn't support all features at this time such as the Scroll slot. Once they implement it that feature of KDocker should just work.
