### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by TCaptainPancake** [user-none/KDocker#141]
**Is your feature request related to a problem? Please describe.**
I don't like it sending a notification when I switch between docked terminal tabs

**Describe the solution you'd like**
A way to disable notifications either system wide or per app

**Describe alternatives you've considered**
Not doing it

**Additional context**
That's all thanks for your work

**Comment by Daxx** [comment]
If you mean you have a terminal window with multiple tabs, you should uncheck the option "Balloon title changes" in the KDocker tray options for the docked terminal app. Use "Save settings" to make it permanent. Also, there's the "-q" (quiet) command line option when launching.

**Comment by TCaptainPancake** [comment]
Thats exactly what I meant thanks sorry I just didn't see it somehow sorry
