### ISSUE TITLE
Option Request: Treat 'close' the same as minimize

### ISSUE THREAD

**Issue by mdavis-xyz** [user-none/KDocker#15]
**Desired behaviour**

When I click the 'close' button for a window (top right of the window, next to maximize and minimize), kdocker minimizes it and sends it to my system tray, just like for the minimize button.

**Existing behaviour**

When I click the 'close' button for a window, kdocker quits the program

Of course there are circumstances when a user would want the quit button to quit the program. I'd like it if there was an option to toggle this behaviour.

**Comment by kupiqu** [comment]
It would be so great to have this option!

**Comment by Daxx** [comment]
I've also spent a lot of time fruitlessly looking for ways of doing this and many of the places I looked, I found comments from the author of a similar app (alltray) looking for the same clues and having the same frustration. :disappointed:

**Comment by promeneur** [comment]
opensuse leap 15.0

hello

perhaps this may help.

i use kdocker to minimize "Android messages" to systray.

 i use skype. skype is docked in systray.
if i use the close button then skype is minimized.

skype is a web app as "android messages" then there is a way to minimize a web app in systray. no ?

thanks for your good job.

**Comment by Daxx** [comment]
> i use skype. skype is docked in systray.
> if i use the close button then skype is minimized.
> 
> skype is a web app as "android messages" then there is a way to minimize a web app in systray. no ?

Several apps have a built-in "Close to Tray" option. Easy for the developer of Skype to add but extremely difficult for a foreigner like KDocker. It's also regarded as 'very rude' to interfere with the behaviour of another app's Close button even when approved by individual users. Thanks for your suggestion.

**Comment by tuxflo** [comment]
> It's also regarded as 'very rude' to interfere with the behaviour of another app's Close button even when approved by individual users
But I think the Butttons are created by the Desktop environment anyways? Some don't even have the classic Minimize, Maximize, Close buttons. So I would not bother too much with that.
I'm looking for a way to minimize the new Thunderbird version back to the tray as one could do in earlier versions with Firetray.

**Comment by qwertychouskie** [comment]
@tuxflo https://github.com/Ximi1970/FireTray/releases or https://addons.thunderbird.net/en-US/thunderbird/addon/minimizetotray-reanimated/

**Comment by NicholasBatesNZ** [comment]
I would really love this as I am looking for a way to minimize Spotify to the tray

**Comment by mase76** [comment]
I would like to have an option to iconify when closing the app. I often hit close by accident, but I want to have the app docked all the time, like evolution or dino-im.

**Comment by Ph0rkoz** [comment]
Yes it would be great since I use this for a vpn client and obviously don't want to close it.

**Comment by Daxx** [comment]
> Yes it would be great since I use this for a vpn client and obviously don't want to close it.

It's not going to happen in KDocker but KDE users can do this:

Click on the title bar's Application Icon -> More Actions -> Special Application Settings -> "Appearance & Fixes" tab: Select "Closable", "Force" and Radio button "No" [OK]

After that you can only use application menu to exit.

**Comment by promeneur** [comment]
In kde plasma environment to get desktop similar version of Google messages, Facebook, Instagram, Twitter, whatsapp  I use their websites. I install them as Chrome webapps.

In case of Chrome webapp the application icon of the window does not get any contextual menu. Is there another 
way to disable the "close" icon action ?

Thanks

**Comment by pnchinmay** [comment]
For spotify, [extract](https://github.com/extract) added a blog's link. Worked for me.
https://github.com/user-none/KDocker/issues/99#issuecomment-980599269

**Comment by ricciolino** [comment]
I am using this extension 

![image](https://github.com/user-none/KDocker/assets/26706348/b8a4ba4c-bf7e-4b46-8b00-c82567c92f43)

and it works great in conjunction with KDocker app 😉
(also the description mention KDocker app)

**Comment by Misko-2083** [comment]
This would be very hard to achieve.
It would require implementing a secondary window manager that runs alongside the primary window manager. Docked app would set the window to override redirect so the main window manager stops managing the window and the secondary window manager to take over the window. It's just too much.
