### ISSUE TITLE
Bash option to not iconify when minimized

### ISSUE THREAD

**Issue by kupiqu** [user-none/KDocker#16]
That would be useful as otherwise task bars in Plasma 5 try to initiate a new instance of the application.

**Comment by user-none** [comment]
The description is a bit misleading but it's the -m option.

**Comment by kupiqu** [comment]
It is not. I'm using -m already. 

I'll try to be more clear. I refer to the option that only appears when you left click on kdocker:

`left click -> Options -> disable "Iconify when minimized"`

I would like to have this option disabled by default by using a bash argument to kdocker.

If there is one, as far as I can see, it is not in the help/man info.

**Comment by user-none** [comment]
-m sets the same flag as the right click menu.

**Comment by kupiqu** [comment]
Then, there must be a bug, as I see exactly the same behavior with and without -m in my call with respect to the right click thing.
In contrast, without -m the window is minimized on startup, while it is not with -m.
To me these are two different things:
1. Minimize or not on startup
2. To iconify, or not, afterwards when the windows is minimized

**Comment by user-none** [comment]
What version of KDocker are you using?

**Comment by kupiqu** [comment]
Version 5.0 from a Ubuntu package.

**Comment by kupiqu** [comment]
Could you test the behavior I described above and, if this is indeed confirmed, please reopen this issue?

Thanks
