### ISSUE TITLE
src/trayitemmanager.cpp:193: possible missing break ?

### ISSUE THREAD

**Issue by dcb314** [user-none/KDocker#17]
Source code is

               } else if (QString::fromLocal8Bit(optarg).compare("x") == 0) {
                    windowName.setPatternSyntax(QRegExp::W3CXmlSchema11);
                } else {
                    QMessageBox::critical(0, qApp->applicationName(), tr("Invalid name matting option: %1.\n\nChoices are: %2.").arg(optarg).arg("n, r, u, w, x"));
                    checkCount();
                    return;
                }

It looks like case e bleeds into case f. I am not sure if this is intended.

Suggest either document the fallthrough or add the missing break.

**Comment by user-none** [comment]
Fixed in 803c882.
