### ISSUE TITLE
Kdocker Start Chrome Web app @ startup

### ISSUE THREAD

**Issue by kendoori** [user-none/KDocker#18]
I am trying to launch the Evernote web app at startup with it under Kdocker control. Am running Mint 17.3. I'm able to get the desired results by manually launching the web app (I used Chrome to save it as a desktop shortcut in a Window). I can then launch Kdocker, point to the app, change the icon and have it live in the tray.

To launch the web app in its own Chrome window, as follows:
/opt/google/chrome/google-chrome "--app=https://www.evernote.com/Home.action#st=p&x=smtp.com&n=5b1aaf6f-a285-45a8-a468-4454d7755b3e"

I tried:
kdocker /opt/google/chrome/google-chrome "--app=https://www.evernote.com/Home.action#st=p&x=smtp.com&n=5b1aaf6f-a285-45a8-a468-4454d7755b3e" -i /home/kschiff/Pictures/Icons/png/256x256/639794_mobile_512x512.png

I get "Cound not find matching window for /opt/google... in the specified time

also tried putting the web app in a script 

kdocker sh ~/bin/evernoteweb.sh -i /home/kschiff/Pictures/Icons/png/256x256/639794_mobile_512x512.png

Same results... what am I doing wrong?

**Comment by user-none** [comment]
It works for me from the command line and as a desktop short cut in the Cinnamon desktop.

When KDocker launches an application it reads the pid of the application as it's started. If for some reason the application launches a different application it will have a different pid.

The only thing I can suggest is using the '-n' option and specify a name to match on. The name is what is the Window title. You may want to play with the '-d' option in case it takes bit to open and set the tile. Also, the name matching can take a regular expression using the QRegExp syntax.

**Comment by kendoori** [comment]
John, sill not working for me.. So sorry to be a needy user, but this is
important for me.. any way that I can talk to you/show you what I'm
experiencing real time?

**Comment by Daxx** [comment]
Works for me unless Chrome browser is already running when it gives the error.

Chrome is a nuisance - 11 PIDs ;)

I've forgotten how kdocker tries to handle this.

**Comment by kendoori** [comment]
Yeah, Chrome is the issue... John mentioned doing a regular expression
using the QRegExp syntax.. the Windows tile includes "Evernote Web" which
is prefixed with whatever the last open note was, which I have no control
over. I don't know how to write that expression. If anyone can write what
that is, that would be helpful to me...

</Kenny>

**Comment by Daxx** [comment]
I can do RegExp but KDocker is not understanding me ;)

My window title is: 'Note 1 | Evernote Web' and I expected this RegExp to match any note name:

kdocker -d10 -er -n 'Evernote\sWeb$' /opt/google/chrome/google-chrome '--app=https://www.evernote.com/Home.action'

( http://doc.qt.io/qt-4.8/qregexp.html#introduction )

I'm guessing that KDocker is not careful enough with the character encoding.
'Note 1 | Evernote Web' can be expressed many ways internally.

I tried using the RegExp hex for 'Web' without success:
   kdocker -er -n '\x0057\x0065\x0062'

-----------

BTW - I use: http://www.giuspen.com/cherrytree/ for notes
Unfortunately, there's no import from Evernote, yet.

**Comment by user-none** [comment]
I forgot you need to set '-e r' to enable regexp matching. I don't know if Mint has the correct version though. Unbuntu only has 4.6 which does not have support for '-e'. There's nothing I can do about them providing a 6 year old version.

**Comment by Daxx** [comment]
Maybe Kenny can try something simpler.
On KDE, I can start KCalc and then dock by RegExp with:
kdocker -er -n '^KCalc$'

**Comment by kendoori** [comment]
Confirmed am running 4.6 with QT 4.8.6.

Should I build new from source? if so, where can I get latest and greatest.

**Comment by user-none** [comment]
4.8 should have the '-e' option.

Source for release is at https://github.com/user-none/KDocker/releases .

**Comment by kendoori** [comment]
Dave, I made myself a shortcut using Chromium instead of Chrome (to get rid
of the Chrome running issue), and updated to Kdocker 4.9 and I got this to
work from startup or CLI:

kdocker -i /home/kschiff/Pictures/Icons/png/256x256/evernote-icon-22.png
/usr/bin/chromium-browser --profile-directory=Default
--app-id=abmjeihjebajmddiahkpfefekehjnmjg

This minimizes Evernote web, and puts it in the tray with an Evernote icon..

Do you know if it's possible to make it that clicking on the tray icon will
restore the application? right now, it seems the only way to restore it, is
to click the icon, the choose "show chromium-browser"

Ideally, it would just restore. I can swear that at some point in my
experimentation I was able to get it to do that, but can't figure that out.

Also, if one closes the Evernote Web window, it closes Evernote Web and
kdocker. Ideally it would just minimize like a true tray application. Do
you know if there's a way to do that?

**Comment by user-none** [comment]
> Do you know if it's possible to make it that clicking on the tray icon will
restore the application?

Double clicking or using the mouse wheel will restore.

> Also, if one closes the Evernote Web window, it closes Evernote Web and
kdocker. Ideally it would just minimize like a true tray application. Do
you know if there's a way to do that?

This is not possible.

**Comment by kendoori** [comment]
John (et. al), last place I'm stuck on this, is that double click doesn't
restore. Single click opens the tray menu, double click opens/minimizes the
tray item. I would like to be able to double click to restore.

I recorded this behavior in the attached.. I'm using 4.9...

​
 kdocker-evernote.mp4
<https://drive.google.com/a/caresight.com/file/d/0B1wPfVpY_gJiWFNLY3BTeUVOUnc/view?usp=drive_web>
​

**Comment by Daxx** [comment]
What does right-click do?

http://askubuntu.com/questions/514766/ubuntu-14-04-systray-icons-open-menu-on-left-click

I'm on 14.04 with KDE and can restore / dock with SINGLE left-click but I can't recall doing anything special to make that happen.

**Comment by user-none** [comment]
This is how Gnome3 tray works. It treats left click like KDE and others (Gnome2) treat right click. The only thing you can do to fix this is to switch desktops environments. The mouse wheel also controls show and hide, try that and see if it works.

**Comment by kendoori** [comment]
Left click:

[image: Inline image 1]

Right click

[image: Inline image 2]

**Comment by Daxx** [comment]
Probably not important now John has answered, @kendoori but I just see "[image: Inline image 1]" rather than actual images.

http://stackoverflow.com/questions/13051428/how-to-display-images-in-markdown-files-of-github

**Comment by kendoori** [comment]
In case someone else stumbles on this, I discovered that turning off
 "support for indicators" in Cinnamon's Settings/General/Miscellaneous
makes single click restore work properly..

Thanks for all of your input.
