### ISSUE TITLE
could not find matching window, Zimbra Desktop

### ISSUE THREAD

**Issue by gslongo** [user-none/KDocker#19]
Hi 

I get this error when lauching Zimbra Desktop 7.3 
![capture-kdocker](https://cloud.githubusercontent.com/assets/5636906/24748902/8124066c-1ac1-11e7-8342-2eb8dd5069b5.png)

Docking manually by lauching kdocker separatly works ...

The command is : 

`kdocker -q /opt/zimbra/zdesktop/linux/zdrun.pl`

Any idea ?

Thanks !

**Comment by user-none** [comment]
If you don't specify the Window name it will try to dock based upon the PID of the application when KDocker launches the application. Name based matching should only be necessary when the application spawns a different process. Meaning it is really just a launcher. I suspect this is the case.

You'll want to play with the -n and -e option.

**Comment by gslongo** [comment]
Hi,

Thanks for answer.

When I use -n "Zimbra Desktop" it docks my firefox o_O

When I do the same without any window opened I get same message as before

Regards
