### ISSUE TITLE
Not working completely on Linux Mint KDE 18.2...

### ISSUE THREAD

**Issue by GitHubCommunityProjects** [user-none/KDocker#21]
It can only use a single icon in the system tray, if two or more icons are placed, the app recognizes them as if it were the first application iconized in the tray, the rest of apps are hidden, and I have to use the option: "Undock All" or close them from the Linux task manager to show and close the apps hidden.

More Info from my Linux PC:

KDE Plasma 5.8.7
KDE Frameworks 5.36.0
Qt 5.6.1

**Comment by user-none** [comment]
I can't reproduce with CentOS 7.
