### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by glolsh** [user-none/KDocker#24]
1. I have issues with compiling on Xubuntu 16.04.3
`g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DTRANSLATIONS_PATH=\"/usr/share/kdocker/i18n\" -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I3rdparty/qtsingleapplication/src -I. -Isrc -isystem /usr/include/X11 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o build/qtlocalpeer.o 3rdparty/qtsingleapplication/src/qtlocalpeer.cpp
3rdparty/qtsingleapplication/src/qtlocalpeer.cpp: In member function ‘bool QtLocalPeer::sendMessage(const QString&, int)’:
3rdparty/qtsingleapplication/src/qtlocalpeer.cpp:160:19: error: variable ‘QDataStream ds’ has initializer but incomplete type
     QDataStream ds(&socket);
                   ^
3rdparty/qtsingleapplication/src/qtlocalpeer.cpp: In member function ‘void QtLocalPeer::receiveConnection()’:
3rdparty/qtsingleapplication/src/qtlocalpeer.cpp:180:26: error: variable ‘QDataStream ds’ has initializer but incomplete type
     QDataStream ds(socket);
                          ^
Makefile:455: recipe for target 'build/qtlocalpeer.o' failed
make: *** [build/qtlocalpeer.o] Error 1
`
2. Could you provide more specific compiling manual for this app? Like install dependencies (other than qt5-qmake on Ubuntu is libqt5x11extras5-dev) or deb package
3. Is there any way make specific configuration of this app for specific application? Like I want to apply this to Spotify Linux Client, I want to minimize on close (yep I know there are issues, but maybe it'll work on this one) or some right-click options like "next, previous, pause".

**Comment by user-none** [comment]
1. I can't reproduce the build error with CentOS 7.
2. I've updated dependencies for CentOS 7 in the INSTALL file. Since every distro has different names and puts different things into their packages I can't provide a list for every possible distro.
3. This isn't possible. It would require knowing a lot of information about a specific app and it relies on the app exposing hooks for other applications to manipulate them.
