### ISSUE TITLE
-q ignored for second and subsequent docks

### ISSUE THREAD

**Issue by Bu11etmagnet** [user-none/KDocker#25]
- Launch KDocker with the `-q` option
- Dock a program. "Balloon title changes" is disabled
- Dock another program. "Balloon title changes" is enabled. It has to be turned off manually.
- Dock another program. "Balloon title changes" is enabled. It has to be turned off manually.
- etc.

This is KDocker 5.0 on Ubuntu 17.10

**Comment by user-none** [comment]
The -q option is a one time use. It's applied to the specific application that's launched and not across everything KDocker docks. If you were to run `kdocker -q app` it would apply to that instance.

If you wan the setting to apply across all applications you need to set it as a global default.

KDocker supports settings in the following way:
1. Command line flag which applies to first app or app launched with KDocker.
2. Application default arguments.
3. Global defaults.
4. KDocker defaults.

1 overrides 2 which overrides 3 which overrides 4.

If you right click on a docked application you'll see options for setting defaults.

**Comment by Bu11etmagnet** [comment]
Where are Application default arguments?
Where are Global defaults? Global as in operating system-level defaults? How do they differ from KDocker defaults?
Where are KDocker defaults?
