### ISSUE TITLE
"Balloon title changes" has to be manually turned off for Every. Single. Docked. Program.

### ISSUE THREAD

**Issue by Bu11etmagnet** [user-none/KDocker#27]
If one does not want "Balloon title changes" , it has to be disabled for every docked program.

*    Dock a program. "Balloon title changes" is enabled. It has to be turned off manually.
*    Dock another program. "Balloon title changes" is enabled. It has to be turned off manually.
*    Dock another program. "Balloon title changes" is enabled. It has to be turned off manually.
*    etc.

This is KDocker 5.0 on Ubuntu 17.10

**Comment by user-none** [comment]
1. Dock one program.
2. Turn off baloon title changes.
3. Go back into the options menu.
4. Go to Save Settings.
5. Choose Global.

Now when you dock any application it will use the saved settings. Settings also allows you to do per app overrides in case you want some apps to have title changes.

**Comment by Bu11etmagnet** [comment]
Where exactly is "Save Settings" in this menu https://imgur.com/vXL3XL8 ?

**Comment by user-none** [comment]
It will be part of the next release (v5.1).
