### ISSUE TITLE
Makefile:331 on opensuse 

### ISSUE THREAD

**Issue by maniat1k** [user-none/KDocker#28]
this the steps I follow to install it:
<pre>
$ qmake
Project MESSAGE: Warning: unknown QT: x11extras
</pre>
then when I run "make":
<pre>
 $ make
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -DTRANSLATIONS_PATH=\"/usr/share/kdocker/i18n\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I3rdparty/qtsingleapplication/src -I. -Isrc -I/usr/include/X11 -Ibuild -o build/qtsingleapplication.o 3rdparty/qtsingleapplication/src/qtsingleapplication.cpp
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -DTRANSLATIONS_PATH=\"/usr/share/kdocker/i18n\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I3rdparty/qtsingleapplication/src -I. -Isrc -I/usr/include/X11 -Ibuild -o build/qtlocalpeer.o 3rdparty/qtsingleapplication/src/qtlocalpeer.cpp
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -DTRANSLATIONS_PATH=\"/usr/share/kdocker/i18n\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I3rdparty/qtsingleapplication/src -I. -Isrc -I/usr/include/X11 -Ibuild -o build/application.o src/application.cpp
In file included from src/kdocker.h:29:0,
                 from src/application.h:25,
                 from src/application.cpp:20:
src/trayitemmanager.h:24:45: fatal error: QtCore/QAbstractNativeEventFilter: No existe el fichero o el directorio
 #include <QtCore/QAbstractNativeEventFilter>
                                             ^
compilation terminated.
Makefile:331: recipe for target 'build/application.o' failed
make: *** [build/application.o] Error 1
</pre>

-----
I'm running OpenSUSE 42.3 with KDE

**Comment by user-none** [comment]
Install the Qt x11extras package which is required.

**Comment by maniat1k** [comment]
@user-none OK, but I installed qtextra but still I does not work

```
$ sudo rpm -qa | grep qtx11
libqt5-qtx11extras-devel-5.6.2-1.3.x86_64
libqt5-qtx11extras-devel-32bit-5.6.2-1.3.x86_64
```

**Comment by maniat1k** [comment]
@user-none please reopen this or maybe share to me the correct  "Qt x11extras". The rpms that I'm install on opensuse looks like that no work..

**Comment by user-none** [comment]
Run ```qmake --version``` and provide the output.

**Comment by maniat1k** [comment]
@user-none thanks for reopenit!

this is the output
```

$ qmake --version
QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib64
```

**Comment by user-none** [comment]
There's you issue, you're building against Qt 4. You need to use Qt5 or KDocker. Qt 4 won't work. The error you're getting for qmke is unstandable because Qt 4 is unable to find a Qt 4 x11extras package. You should have something like qmake5 which you need to use to generate the Makefile. Or you may  need to install Qt 5 development packages. I don't know the specific of how OpenSUSE distributes their Qt major versions.

**Comment by Daxx** [comment]
https://stackoverflow.com/questions/39735998/make-qmake-use-qt5-by-default
