### ISSUE TITLE
Option request: Restore to current desktop

### ISSUE THREAD

**Issue by Druco** [user-none/KDocker#32]
Currently when a window is restored, it is restored to the desktop it was minimized on and focus is switched to that desktop.  I would like to see an option which would allow an application to always be restored to the current desktop.  If the window was currently open on a different desktop, clicking the icon would simply move the window to the current desktop.

I like to be able to leave my browser running and then just pop it up on whatever desktop I happen to be on at the time rather than switching back and forth between desktops.

**Comment by Daxx** [comment]
What you described is the behaviour of your window manager.

Assign browser to All Desktops?
e.g. KDE/Kwin

![all_desktops](https://user-images.githubusercontent.com/154675/37858771-cdc9c308-2f01-11e8-90aa-41c48e2d2a2b.jpg)

**Comment by Druco** [comment]
Thanks for the response but All Desktops behavior is not what I intended to convey.  Currently I am using a Firefox addonn called  Firetray which is not available for the new Quantum releases, so I am trying to find something to support that functionality and here is how I use it:

I'm on Desktop 1 where I'm doing some development and I want to know the syntax of a particular function  so I pop up the browser and search for the command, I ALT-TAB back and forth a few times to get the details right and leave the browser in the background because my editor is maximized and I don't see the browser unless it is on top.  Then I get a notification that I got some mail so I switch to Desktop 2 where my email is. Now 99% of the time, I don't want my browser up on the email desktop because I don't need it but this time someone wants to know what that restaurant we went to was called and I can't remember exactly so now and only now do I want to pop up the browser onto Desktop 2.  Then I switch to Desktop 3 where I have a solitaire game going. It doesn't fill the entire screen and I never want the browser when I 'm on that desktop so if I have the browser on All Desktops I have to minimize it.

I realize that this use case may not be very common but I wanted to make the suggestion in case it wasn't all that complicated to add.

**Comment by Daxx** [comment]
I'm confident that KDocker is not the place to solve this.

The work-flow you describe doesn't sound too uncommon. KDE/Plasma has recommended for a long time to use Activities over Desktops but I just found that clicking on a KDocker icon behaves the same.

I hope you can now focus on a different solution (maybe a shortcut key that runs a script) or something less messy. You should still be able to comment after John has closed this issue.

**Comment by Druco** [comment]
Not a problem, I looked at the code and it looks like if I just want to permanently change the functionality and don't bother to add a command line option, I will only need to comment out a couple of lines to do what I want. Thanks anyway.

**Comment by Druco** [comment]
Here's a modified copy of trayitem.cpp which implements this. The two modified functions are restoreWindow() and toggleWindow(). It can probably be done somewhat cleaner but this seems to do the job. By the way I want to thank you for commenting the code so well, it makes working on it so much easier than most Open Source code.
[trayitem.cpp.txt](https://github.com/user-none/KDocker/files/1859688/trayitem.cpp.txt)

**Comment by Daxx** [comment]
Sorry, I gave you wrong info on this issue -- my confidence was misplaced. Oops.
I'm glad you found a solution which looks fine. It's on my TODO list to add as an option.

**Comment by Daxx** [comment]
Druco, Could you check that my changes on https://github.com/Daxx/KDocker do what you expect?
Feel free to be ultra-critical and we can submit a pull request to John from there.
Seems to work for me. Thanks.

**Comment by Druco** [comment]
I tried the updated (Daxx) version and it seems to work fine. I'd say go ahead with it. Thanks a lot.

On another unrelated topic, when I run firefox with KDocker, I get notification popups every time I open a site or add a new tab. Do you know if anyone else sees this behavior and if so, is there anything that can be done to get rid of this. I tried to figure out if there was a way to setup a notifyrc file that might alleviate this but so far I haven't had any luck with that. Anyway thanks again for the support.

**Comment by Daxx** [comment]
Thanks Druco.

(Sounds like you need to uncheck "Balloon title changes" option and then Save settings specifically for Firefox or save as Global default (all new))

**Comment by user-none** [comment]
Merged.
