### ISSUE TITLE
"Iconify when minimized" and "-m" option

### ISSUE THREAD

**Issue by gusbrs** [user-none/KDocker#34]
I've been trying to dock some applications of mine with `kdocker` (which is working very nice overall, thank you!), but I'm having some difficulties with one issue.

I'd like to use `kdocker` with the option "Iconify when minimized" disabled. Of course, I can always uncheck it, after having docked the application, but I'd like to do so with the command options.

As far as I grasped from the source, the "-m" option corresponds to "IconifyMinimized" internally. However, the "-m" option is described in the help as "Keep application window showing (don't hide on dock)", which actually corresponds to what happens when you use it. And indeed, the "Iconify when minimized" option in KDocker's menu is checked when the "-m" option is used. And if I minimize the application, it goes to the tray.

Apparently (I may well be missing something though), the set "-m" option and "InconifyMinimized" is sort of controlling two things, what happens when you first dock your application, and what happens when you minimize it after it is already docked.

I think both things might indeed be dealt with this option, as long as "Iconify when minimized" is set to false when the "-m" option is used.

(I'm running a Linux Mint 18.3 with a Mate desktop environment, if that's relevant).

So I kindly request you took a look on this (or explain me what I may be missing). And thank you very much for the nice application.

**Comment by Daxx** [comment]
Which version are you using? ( kdocker -v )

> And indeed, the "Iconify when minimized" option in KDocker's menu is checked when the "-m" option is used.
It shouldn't be checked in that case unless you've changed and saved the default value.
By default, "InconifyMinimized" is the one option that defaults to true. The "-m" flag negates it.

> And if I minimize the application, it goes to the tray.
That behaviour is unaffected by "-m" option.

So, "-m" will dock but not minimize the app.
Omit "-m" to dock *and* minimize.

[ As far as I'm aware - feel free to challenge ;) ]

**Comment by gusbrs** [comment]
Mmh, I see. I'm glad to know it's already dealt with in the current version. Thank you very for your prompt and precise response. And, again, for the application itself!

(And sorry for the fuss due to an outdated version...)

**Comment by Daxx** [comment]
If the original author is out there, somewhere, I redirect your thanks in that direction. :)

**Comment by saulfautley** [comment]
Sorry to bring up this old issue, but it seems the reported behaviour is still occuring in the latest master build, i.e. using the `-m` option force disables `Iconify when minimized`.

I'm trying to launch an app with KDocker without it being minimized to the tray immediately, but still minimize to the tray upon manual minimizing.

This currently seems impossible as launching with `-m` achieves the first part but not the second, and vice versa without `-m`. Using the `Save settings` option or editing `KDocker.conf` seems to have no effect either way.

**Comment by Daxx** [comment]
Possible workaround at https://github.com/user-none/KDocker/issues/84 ?
