### ISSUE TITLE
Feature request: Icon reload

### ISSUE THREAD

**Issue by aoe-mak** [user-none/KDocker#36]
Hey, 

it would be nice if kdocker is able to reload or load another icon while running.

I want to use it for Thunderbird and a mail check via a plugin which can run a command.
Unfortunately other plugins for these purposes (with icon change) are not supported anymore.
I was hoping to fix that with kdocker.

Cheers

**Comment by Druco** [comment]
This would be a great addition given the latest Thunderbird update.

**Comment by xdenyer** [comment]
I'm also using KDocker to tray Thunderbird, plus this hacky script with https://addons.thunderbird.net/en-US/thunderbird/addon/mailbox-alert/ to create an icon on new mail;

```
#!/bin/bash
if ! pgrep -f yad.*mail-mark-unread.*thunderbird &> /dev/null 2>&1; then
yad --notification --image="mail-mark-unread" --listen --command="sh -c 'thunderbird ; pkill -f yad.*mail-mark-unread.*thunderbird'" &
fi
```

Yad would probably also do what you're wanting, it's pretty flexible.

**Comment by dmarkdvt** [comment]
Moved to another company. :D I will try that.

**Comment by dmarkdvt** [comment]
> I'm also using KDocker to tray Thunderbird, plus this hacky script with https://addons.thunderbird.net/en-US/thunderbird/addon/mailbox-alert/ to create an icon on new mail;
> 
> ```
> #!/bin/bash
> if ! pgrep -f yad.*mail-mark-unread.*thunderbird &> /dev/null 2>&1; then
> yad --notification --image="mail-mark-unread" --listen --command="sh -c 'thunderbird ; pkill -f yad.*mail-mark-unread.*thunderbird'" &
> fi
> ```
> 
> Yad would probably also do what you're wanting, it's pretty flexible.

Can you do me a favour and split the commands and add some explanation/comments? :)

**Comment by dmarkdvt** [comment]
Can not test the alternative because https://addons.thunderbird.net/en-US/thunderbird/addon/mailbox-alert/ is not compatible with Thunderbird 68.

**Comment by dmarkdvt** [comment]
Currently running Kdocker with the suggestion from @xdenyer.

```
#!/bin/bash
# /usr/local/bin/thunderbird
# chmod -v +x /usr/local/bin/thunderbird

/usr/bin/kdocker -i ~/docs/thunderbird.png -m -q /usr/bin/thunderbird &
```

```
#!/bin/bash
# 

# https://bugzilla.mozilla.org/show_bug.cgi?id=1482674
while true
do
	inotifywait -m ~/.thunderbird/PROFILE/Mail/localhost/Inbox.msf -e modify |
	while read output;
	do
	    sleep 1
	    icon_already_exists=$(pgrep -f yad.*mail-mark-unread.*thunderbird)
	    if [ -z "$icon_already_exists" ]
	    then
	        yad --notification --image="mail-mark-unread" --listen --command="sh -c '/usr/local/bin/thunderbird ; pkill -f yad.*mail-mark-unread.*thunderbird'" &
	    fi
	done
done
```

**Comment by xdenyer** [comment]
Ah, you've gone with monitoring the mailbox file directly -- I find I tend to modify mailbox items, and went with monitoring a (silent) sound file that Thunderbird's configured to play on new mail. But glad the approach works for you, inotifywait seems like a really useful tool.

If anyone else wants, now that Thunderbird's broken the alert extension...

https://bugzilla.mozilla.org/show_bug.cgi?id=1482674

```
#!/bin/sh
inotifywait -m -e access /home/username/.myscripts/watch_silent.wav |
while read output;
do
    sleep 1
    icon_already_exists=$(pgrep -f yad.*mail-mark-unread.*thunderbird)
    if [ -z "$icon_already_exists" ]
    then
        yad --notification --image="mail-mark-unread" --listen --command="sh -c 'thunderbird ; pkill -f yad.*mail-mark-unread.*thunderbird'" &
    fi
done
```

It'd be nice if the Thunderbird devs hopped off the Gnome bandwagon and better supported normal desktop environments.

And on-topic, being able to update KDocker icons would be useful.

**Comment by dmarkdvt** [comment]
@xdenyer Now I got it. Thx. Your approach is fixing my current problem with an icon popping up even when I delete a mail. But you know it already and solved it quiet funny. Thx for the inspiration.

**Comment by xdenyer** [comment]
For info (was googling earlier) the developer has been able to update the Mailbox Alert plugin, which makes it straightforward again to run a script on new mail: https://tjeb.nl/Projects/Mailbox_Alert/

They note; "Open issue: I am aware that the custom Filter action for Mailbox Alert isn't working (due to the removal of XBL bindings), but have yet to discover how the new interfaces work. In recent versions of Thunderbird (>63) it is currently not possible to set the target action for the MailboxAlert Filter."

Tested working with Thunderbird 68.2.2, I'm using the script I was originally;
```
#!/bin/bash
if ! pgrep -f yad.*mail-mark-unread.*thunderbird &> /dev/null 2>&1; then
	yad --notification --image="mail-mark-unread" --listen --command="sh -c 'thunderbird ; pkill -f yad.*mail-mark-unread.*thunderbird'" &
fi
```

**Comment by sonofevil** [comment]
All that's needed is something like this:

dBus:
`editWindow 	(wID windowConfig)`
command options:
`--edit wID [options]`
