### ISSUE TITLE
Feature request: Option that minimize just minimize and not dock to tray

### ISSUE THREAD

**Issue by aoe-mak** [user-none/KDocker#37]
Hello,

I just click on the icon if I want to dock a program.
I use ctrl-alt d to minimize all windows at once but a program running via kdocker just gets docked.

Would be awesome :)

**Comment by Daxx** [comment]
What happens after you uncheck the "Iconify when minimized" option for docked apps?

I guess Ctrl+Alt+D undoes 'minimize all' for the other windows. Gnome desktop? (I'm KDE).

**Comment by aoe-mak** [comment]
It works when I disable it. Can I set this option via command line?

Ubuntu 16.04.4 LTS
XFCE 4.1.2 (Gnome)
Kdocker 4.6-2

**Comment by Daxx** [comment]
**-m**&nbsp;&nbsp;&nbsp; Keep application window showing (don't hide on dock)

**Comment by aoe-mak** [comment]
It is not solved. -m is not doing what I wanted.

**Comment by user-none** [comment]
Try using a current release. You're 5 releases behind.

**Comment by aoe-mak** [comment]
It works with the current release. Thank you.
