### ISSUE TITLE
KDocker will not make

### ISSUE THREAD

**Issue by Scotxd** [user-none/KDocker#38]
Downloaded tar.gz, installed required dependencies for Ubuntu 18.04.1 LTS, ran qmake, but make fails with "src/xlibutil.h:35:10: fatal error: Xmu/WinUtil.h: No such file or directory
 #include <Xmu/WinUtil.h>"
Not sure if this is an issue with qmake, as after installing qt5-default i also had to install libqt5x11extras5-dev, but please let me know.

**Comment by user-none** [comment]
Please see the the INSTALL file which lists dependencies that need to be installed to build. You are missing some of the X11 ones.

**Comment by Scotxd** [comment]
Where would I find these dependencies?

**Comment by Scotxd** [comment]
Never mind, a quick look on the ubuntu website helped.
