### ISSUE TITLE
App iconifies on desktop change in KDE 5.14

### ISSUE THREAD

**Issue by Druco** [user-none/KDocker#43]
I am running KDocker 5.2 and OpenSuse tumbleweed just updated from KDE/Plasma 5.13 to 5.14 and now switching to a different desktop iconifies any docked applications.  This didn't happen with KDE 5.13 so something has changed in KDE which affects KDocker.
This is only an annoyance for me but as more distros move to 5.14 it might be a bigger issue with other users.

**Comment by Druco** [comment]
I did a little more work on this and found that it only happens when the "Iconify when minimized" flag is set so as a workaround I am just going to unset this. 

The problem appears to be in the function TrayItem::propertyChangeEvent where a WM_STATE property is being generated when either the minimize button is clicked or when the virtual desktop is changed and at least with the parameters currently being checked, the events are indistinguishable.

**Comment by user-none** [comment]
Fix merged.
