### ISSUE TITLE
KDocker doesn't restore maximization for titlebarless Firefox/Thunderbird

### ISSUE THREAD

**Issue by birdie-github** [user-none/KDocker#49]
Steps to reproduce:

1) Run any of these applications under kdocker
2) Maximize it if it's not already maximized
2) Minimize it
3) Restore it by clicking its systray icon

Result: the application will not be maximized (though visually it will occupy the entire screen)

Expected result: the application is maximized 

Additional info:

I'm running Fedora 29 + XFCE

Firefox must have this option enabled: `browser.tabs.drawInTitlebar = true`

Thunderbird must have this option enabled: `mail.tabs.drawInTitlebar = true`

**Comment by qwertychouskie** [comment]
I think this is a FF/TB bug, same problem when un-fullscreening a youtube video.

**Comment by birdie-github** [comment]
> I think this is a FF/TB bug, same problem when un-fullscreening a youtube video.

I don't understand how that's relevant at all. When I restore FF/TB from the task bar - everything works just fine.

**Comment by Ducvoccer** [comment]
up

**Comment by birdie-github** [comment]
@user-none 

Sadly this is reproducible in version 6.0.

I'm using [Thunderbird 128.2.0esr](https://ftp.mozilla.org/pub/thunderbird/releases/128.2.0esr/linux-x86_64/) under Fedora 40/XFCE.

**Comment by birdie-github** [comment]
@user-none 

Sadly this is reproducible in version 6.0.

**Comment by birdie-github** [comment]
@user-none

Sadly this is reproducible in version 6.1.

**Comment by user-none** [comment]
#49 is not a bug in KDocker. It is an issue with the window manager you're using.
