### ISSUE TITLE
Kodi cant be docked

### ISSUE THREAD

**Issue by Raffinade** [user-none/KDocker#51]
Hi Guys, 
i have the problem that kdocker can't put kodi in the tray. 
If i make 
`kdocker -w id(of kodi) `

the taskbar dissapear. If i make 
`kdocker kodi`

I get the warning:
`Could not find a matching window for kodi in the specified time: 5 seconds.`

and in the shell i get this warning:
```libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the -global-isel-abort option: may only occur zero or one times!
libva info: va_openDriver() returns 0
```
Is there a solution for kodi, i want to start it minimized as i login.

Greetings
Raffinade

**Comment by rapgro** [comment]
Normally, kodi runs in fullscreen mode. Might be of interest how you would or manage to run kodi in a scaled window.

**Comment by Raffinade** [comment]
Kodi - Settings - System - Display - Display Mode - Windowed

**Comment by Raffinade** [comment]
Why is that closed? I didnt get an answer on my question? I can scale kodi but i cant put it in the tray.

**Comment by Raffinade** [comment]
Why is that closed? I didnt get an answer on my question? I can scale kodi but i cant put it in the tray.

**Comment by qwertychouskie** [comment]
@Raffinade It seems you accidentally closed the issue.
