### ISSUE TITLE
Issues with Kmail/Akondadi

### ISSUE THREAD

**Issue by iandoug** [user-none/KDocker#52]
Hi

Are there known issues with Kmail/Akonadi conflict?

I installed this from portage (using Gentoo), and used it to minimise Zotero, and set it visible in tray, and immediately Kmail/Akonadi started playing up ... Akonadi keeps needing to be restarted.

I uninstalled KDocker but issues persist, suppose I must try a reboot even though KDocker does not show up in running processes. Restarting desktop didn't help.

**Comment by user-none** [comment]
If you do not have KDocker installed, rebooted and the issue persists this is not applicable to KDocker.

**Comment by iandoug** [comment]
I re-installed and seems to work fine now. Don't know what issue was. Thanks.
