### ISSUE TITLE
balloon title change, what does that mean ?

### ISSUE THREAD

**Issue by promeneur** [user-none/KDocker#53]
"balloon title change", what does that mean ?

how to use it ?

thanks

**Comment by Daxx** [comment]
Balloon messages refer to "speech bubbles" which are just notifications, normally appearing in the system tray (panel) area.
KDocker monitors windows under its control and, if their window title changes, a notification is sent to the operating system to be displayed (ballooned).
Some sites update the title bar when something of interest happens: Not a great example but Twitter prepends the number of new posts in parentheses.
It would also notify whenever you manually select another tab or when monitoring the price of bitcoin ... which is almost entirely useless and intensely irritating but it's available for whoever finds a need for it. So far, that hasn't been me.
