### ISSUE TITLE
kdocker do not remain last settings

### ISSUE THREAD

**Issue by Cherkah** [user-none/KDocker#55]
hi and thanks for your app

kdocker do not keep an history of last app used in so far as it can't reload the settings (icon ,iconify..& skip... stuff). But will can it?

does it possible to change the "exec" field of an app.desktop so as to launch  kdocker same time?
exemple: 'kdocker spotify ....'

regards

kde + debian testing

**Comment by Daxx** [comment]
Settings are stored using a Qt QSettings object and should be found in:
~/.config/com.kdocker/KDocker.conf

Please attach that file to your reply and show the output from:
`kdocker -v`

**Comment by Daxx** [comment]
Regarding app.desktop, any valid 'exec' field should be accepted.
Beware that it might be overwritten by a new version of 'spotify' or the app that owns the .desktop file.

**Comment by Cherkah** [comment]
my ~/.config/com.kdocker/KDocker.conf is empty
`kdocker -v
KDocker version: 5.0
Using Qt version: 5.11.3`

lauching spotify (flatpak) with docker gave to me:
`$ kdocker /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=spotify --file-forwarding com.spotify.Client @@u %U @@

Icon theme "gnome" not found.
/app/extra/bin/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/bin/spotify)
/app/extra/share/spotify/spotify: /app/lib/libcurl-gnutls.so.4: no version information available (required by /app/extra/share/spotify/spotify)
/proc/self/exe: /app/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
[0824/000203.951062:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
`

**Comment by Daxx** [comment]
> my ~/.config/com.kdocker/KDocker.conf is empty
> `kdocker -v`
> `KDocker version: 5.0`
> `Using Qt version: 5.11.3`

It's empty because your version doesn't save settings ...

https://nachtimwald.com/2018/02/18/kdocker-5-1-released/

**Comment by Daxx** [comment]
Re; .desktop problem ...

> lauching spotify (flatpak) with docker gave to me:
> `$ kdocker /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=spotify --file-forwarding com.spotify.Client @@u %U @@`
> 
> `Icon theme "gnome" not found.`

None of that is related to KDocker.
You'll have to do some extra work. See these two pages for tips / clues:

https://github.com/user-none/KDocker/issues/42

https://askubuntu.com/questions/461434/lubuntu-how-to-execute-2-commands-in-desktop-file

**Comment by Cherkah** [comment]
ok  i'll investigate this tips
just to know there are more than 1  year since laste  kdocker version was realesed.
why debian repo keep V5.0 and not V5.1

**Comment by Venegrad** [comment]
> /.config/com.kdocker/KDocker.conf is empty

same issue
