### ISSUE TITLE
Detect if an app is already running and don't show an error if it's launched again

### ISSUE THREAD

**Issue by birdie-github** [user-none/KDocker#58]
Certain apps like Firefox or Thunderbird by default (if you don't use profiles) allow to have only a single running instance however if you try to launch them more than once, KDocker spews this error message: "Could not find a matching window for thunderbird in the specified time: 5 seconds" which is obviously not correct.

I guess the easiest workaround will be to add a command line option for such applications.

**Comment by Daxx** [comment]
Organise yourself better ;)

Couldn't you write a small shell script (tb) to launch thunderbird which tests to see if it's already running, then call KDocker? Or a general script (kd xxapp) to take care of that?

**Comment by drujd** [comment]
I did exactly that. But it would be nice to have a way of reopening the window from tray by some command (and ideally focus it, but that I can do using wmctrl). There does not seem to be a way to open iconified app's window by any kdocker cli command - only by clicking on the icon.
