### ISSUE TITLE
Is Lxpanel supported?

### ISSUE THREAD

**Issue by gerroon** [user-none/KDocker#59]
Hi

Does this app support LXpanel ?

thanks

**Comment by Daxx** [comment]
LXpanel features a notification area (system tray).
Standard X11 stuff. Should dock your apps into there.

Let us know when you've tried it ;)

**Comment by gerroon** [comment]
Hi

Yes I tried it but I can`t get icons with some apps, I get a question mark with electron apps. And also it does not remember the set icon, but I guess that is better than alltray in my view.

**Comment by user-none** [comment]
v5.5 reworked how icons are read from windows and should be better now.
