### ISSUE TITLE
KDocker will not build on Arch Linux

### ISSUE THREAD

**Issue by MormonJesus69420** [user-none/KDocker#62]
Hello! 

I have an issue when I try to install KDocker on my computer. I am currently running on kernel 5.4.13-arch1-1 and have made sure that I have all dependencies installed. However when I try to install it through yay (AUR package manager) I get following error message:

```bash
make: *** [Makefile:1312: build/trayitem.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Error making: kdocker
```
There's also another person who experienced this problem yesterday, and posted it on KDocker's AUR page. So it does not look like it's an isolated incident.

Attached a file with complete output from installation process. Error occurs at line 51
[errorlog.txt](https://github.com/user-none/KDocker/files/4090953/errorlog.txt)

**Comment by user-none** [comment]
The build issue is due to a define conflict between X and Qt. It was fixed in trunk not too long ago in 43379a67. A release hasn’t been made with the fix yet. Right now you’ll need to either pull the change in as a patch to the arch build script or build trunk.
