### ISSUE TITLE
Lutris: Docked twice when you install games form their website

### ISSUE THREAD

**Issue by Zeioth** [user-none/KDocker#66]
**Severity**: Low

If I install games from inside Lutris, everything works as expected, but when I install games from their website, the docker is created twice.

**Comment by Daxx** [comment]
Steps to reproduce?

**Comment by Zeioth** [comment]
kdocker lutris
    click install [here](https://lutris.net/games/path-of-exile/)

Two things may happen:
    1. You get an error "This window is already docked" -> Would be cool to have a way to silence this
    2. 10% of the time, is docked twice.

This is a minor bug in comparison with #65

**Comment by Zeioth** [comment]
Lutris is implementing its own tray icon, so this issue can be closed.
