### ISSUE TITLE
[support]  how to make it keep program in tray after restart?

### ISSUE THREAD

**Issue by omega3** [user-none/KDocker#71]
I installed KDocker, docked application and it worked ok. I added KDocker to system settings autostart. But after reboot I didn't see KDocker icon in system tray but only this KDocker pointer to choose application to dock.

I want to have after each system start KDocker icon visible in system tray so that when I open a program that is assigned to dock I don't have to make docking procedure again, but only click on KDocker icon to minimize application to system tray. Does KDocker have a configuration file where it stores rules for applications, so that when I reopen the application I don't need to dock again?
What are the proper steps? 

Can KDocker be permanently integrated with Plasma systemtray?

**Comment by Kandelai** [comment]
Same here. I would add to @omega3 comments that if you close the app, it removes it completely from KDocker, so you have reapply every time. I have even used the save Globally feature, but it doesn't save the apps the next time you use them. Without these functions, the app is kind of useless unless you want to spend your time setting up each app constantly.

**Comment by kozar** [comment]
You may run your application like this (and add it to auto-launch):
`kdocker thunderbird`

I've found this by reading the help:
`kdocker -h`

**Comment by mateusviccari** [comment]
Some apps, like kdocker, run from another program called "gapplication" which I suppose is the program that lets you run gnome applications on KDE.
By trying to run it with kdocker using the syntax:
`kdocker gapplication launch org.rnd2.cpupower_gui`
it gives the message "Could not find a matching window for gapplication in the specified time: 5 seconds."
