### ISSUE TITLE
The window you are attempting to dock does not seem to be a normal window

### ISSUE THREAD

**Issue by KuenzelIT** [user-none/KDocker#75]
Hi,

I'm always getting the message `The window you are attempting to dock does not seem to be a normal window` when trying to dock any window. I tried different applications, but the message is always the same. I don't know what a normal window is in this context.

I'm using Linux Mint 19.3 Cinnamon and just installed KDocker from the application manager of Linux Mint.

I couldn't find an issue with this problem. Do you have an idea?

Thanks!

**Comment by Daxx** [comment]
A 'normal' window usually means any visible window created by the application itself.

When an application starts, the window manager shows an entry for it (it's just another window) on the task bar (panel) but if you select that, kdocker will give the error message you're seeing.

**Comment by KuenzelIT** [comment]
Ouuukay, I didn't get that. For some reason I assumed I had to choose from the task bar. Now its working, thank you!
