### ISSUE TITLE
Command timing out under set maximum time?

### ISSUE THREAD

**Issue by dairefagan** [user-none/KDocker#79]
On Ubuntu 20.04.1 Gnome I have added a startup command:

`kdocker cyrptomator -n cryptomator -d 15`

which I intend on boot to launch cryptomator with kdocker, grab the window with the name cryptomator, and allow 15 seconds for the window to appear.

Sometimes this works, sometimes kdocker does not minimise Crptomator and instead displays the error: `Could not find matching window for cryptomator in the specified time: 5 seconds`, and this is despite the Cryptomator window being visible in front of the kdocker error.

As visible in this [screenshot](https://i.imgur.com/aXOdKLm.png).

Is my syntax wrong?

**Comment by dairefagan** [comment]
Skipping the taskbar with `kdocker -t -d 15 cryptomator` has been working well across several reboots. The delay is probably not even necessary but I am leaving it in for now as a precaution.

**Comment by Daxx** [comment]
Usage: kdocker [options] [command] -- [command options]

Options before command, so ...

`kdocker  -n CRYPTOMATOR  cryptomator`

**Comment by dairefagan** [comment]
> Usage: kdocker [options] [command] -- [command options]
> 
> Options before command (as in your second comment), so ...
> 
> `kdocker -t -n CRYPTOMATOR cryptomator`
> 
> Otherwise all the (unknown) options are passed to cryptomator and none to kdocker.

Thank you for the clarification.
