### ISSUE TITLE
src/trayitemmanager.cpp:253: bad array size

### ISSUE THREAD

**Issue by dcb314** [user-none/KDocker#80]
src/trayitemmanager.cpp:253:38: warning: division 'sizeof (char*) / sizeof (char)' does not compute the number of array elements [-Wsizeof-pointer-div]

Source code is

     if (((sizeof(optarg) / sizeof(*optarg)) > 2) && ((optarg[1] == 'x') || (optarg[1] == 'X'))) {

**Comment by user-none** [comment]
This code has been rewritten.
