### ISSUE TITLE
Tray icon is always a question mark 

### ISSUE THREAD

**Issue by Victor239** [user-none/KDocker#81]
How do I get KDocker to use the unique desktop icon for each application?

 If I use the "Set Icon" option by right-clicking the docked application I can set the icon temporarily, but when the application is closed and then reopened it will be back to the question mark icon again.

**Comment by Justinzobel** [comment]
I've got the same issue here with 5.3 release.

**Comment by Justinzobel** [comment]
Is it possible to save preferences for each application that is docked to ~/.config/KDockerrc?

**Comment by Daxx** [comment]
For version 5.1 and above, per-application and global settings are stored wherever Qt defaults to.
For me, it's "~/.config/com.kdocker/KDocker.conf" but there's no need to edit that.

Set Icon ... ( e.g. for "DockedApp4" )
Save settings ... ( "DockedApp4 only" option -- because Global (all new) would be silly ;) )

**Comment by Justinzobel** [comment]
OK, so there seems to be a bug in the menu display.

The first time I right-click on a docked icon I get the below, the Save settings item is cut off:
![image](https://user-images.githubusercontent.com/1370117/110182931-af1e7800-7e5d-11eb-80a9-d1864ba4e0ea.png)

The second time I right-click on the docked icon I get the full menu with the Save settings item.

Not sure if this is a Plasma/kwin issue or kdocker.

**Comment by Daxx** [comment]
Wow, that's awful.
I've never seen that from KDocker or from any other app that I can recall.
I rely on QMenu to do all those calculations for me. No warnings in the docs.
I assume you compiled it yourself; please show `kdocker -v` output for Qt version.

Not much help from these search results:
[QMenu opens first time off screen](https://forum.qt.io/topic/56576/qmenu-opens-first-time-off-screen)
[How to prevent QMenu from going out of the main window](https://stackoverflow.com/questions/59468895/how-to-prevent-qmenu-from-going-out-of-the-main-window)

**Comment by Justinzobel** [comment]
I didn't compile myself, this one is from the Solus repository.

```
kdocker -v
KDocker version: 5.2
Using Qt version: 5.15.2
```

How it's compiled by the Solus team: https://dev.getsol.us/source/kdocker/browse/master/package.yml

**Comment by Justinzobel** [comment]
I might compile 5.3 and test.

**Comment by Justinzobel** [comment]
Same with 5.3 unfortunately.

**Comment by user-none** [comment]
5.5 has changes to how the tray icon is read from the window and works better now.
