### ISSUE TITLE
'Failed to grab mouse'

### ISSUE THREAD

**Issue by dairefagan** [user-none/KDocker#82]
I have been using the follow autostart command on Ubuntu 20.04 fine the last few months: `kdocker -t -d 15 cryptomator` but this stopped working last night. It may be unrelated but I removed a commit=120 line in fstab from my BTRFSonLUKS mounts last night and since I have noticed Kdocker is outputting an error on login: _Could not find a matching window for cryptomator in the specified time: 15 seconds_ - although this appears in front the cryptomator window itself which loads about 10 seconds earlier. KDocker itself opened fine for me in the past but now despite disabling autostarts, rebooting, and reinstalling, I still receive the error: `Failed to grab mouse`. I wonder if the two issues are related? I am curious as to why this outputs invalid window ID despite this being the ID `xwininfo -name "Cryptomator"` displays: `kdocker -t -w 0x2c00003 cryptomator`

What did work was changing the autostart to: `kdocker -t -d 15 -n Cryptomator cryptomator` although I still receive the error Failed to grab mouse when trying to open KDocker on its own, I wanted to flag this and ask if there is anything I can do to fix this please?

**Comment by lithium-umbreon** [comment]
@user-none any way to fix this?

**Comment by Daxx** [comment]
> @user-none any way to fix this?

Yes ... give it 30 seconds, or more!

Clearly `kdocker -t -d 15 -n Cryptomator cryptomator` works but autostart sets kdocker running before the desktop is fully ready.

I wonder if this kind of thing is the reason for kdocker having a score of 2/5 stars in the software manager.
cryptomator appears to be distributed as an AppImage (the one I found was).
Inside that is a java app -- the app that owns the window that kdocker is unable to find because it doesn't belong to the cryptomator process itself.

So, the solution is as @dairefagan found -- provide the window name so that kdocker has something to look for.

I'm not getting `Failed to grab mouse` on 20.04, so what's to fix?

**Comment by lithium-umbreon** [comment]
> > @user-none any way to fix this?
> 
> Yes ... give it 30 seconds, or more!
> 
> Clearly `kdocker -t -d 15 -n Cryptomator cryptomator` works from a terminal but autostart sets kdocker running before the desktop is fully ready.
> 
> I wonder if this kind of thing is the reason for kdocker having a score of 2/5 stars in the software manager.
> cryptomator appears to be distributed as an AppImage (the one I found was).
> Inside that is a java app -- the app that owns the window that kdocker is unable to find because it doesn't belong to the cryptomator process itself.
> 
> So, the solution is as @dairefagan found -- provide the window name so that kdocker has something to look for.
> 
> I'm not getting `Failed to grab mouse` on 20.04, so what's to fix?

After launching it once it refuses to start unless started from the terminal or software center for me. Both an issue on 20.04 and 20.10.
Tried reinstalling it but that did nothing to solve this issue, I'm guessing it probably doesn't have any problems and it's just my setup that's causing this.

**Comment by Daxx** [comment]
Maybe check this: https://medium.com/@habibdhif/full-guide-to-install-cryptomator-properly-on-ubuntu-using-appimage-9ca0a473ca98

I think the last line of the .desktop (kdenlinve) is leftover, so remove or change it.

**Comment by FixitmanArizona** [comment]
Had this issue ONCE in _Xubuntu 22.04_ but I can't remember why it did this. I didn't have it properly configured yet, however. So, it's telling you "try again" I suppose.;)
Now I have it set up and only use it for a single application, _qpaeq_ (or it eats CPU with 3 or more hidden docked applications  even though they don't eat CPU all opened without _kdocker_ - not recommended.)

**Comment by user-none** [comment]
Can't reproduce on Ubuntu 24.04
