### ISSUE TITLE
Full-form command line options

### ISSUE THREAD

**Issue by samuelznewton** [user-none/KDocker#85]
This is not at all a serious issue, but I often prefer using full-form command line options (e.g. --help instead of -h), and these are strangely absent from KDocker.  No pressure, but if you had a couple minutes to add those in, they would at least see a little use from me. :)

**Comment by Daxx** [comment]
Great idea! You've got the job :) -- KDocker options are a mess.

1. Make a list of all the full-form options you would suggest (you can drop them as a comment in this thread for future reference).
2. Even if you're not a C++ hacker, clone the KDocker repo 
3. Hack the [pod file](https://raw.githubusercontent.com/user-none/KDocker/master/helpers/kdocker.pod) ([pretty version](https://github.com/user-none/KDocker/blob/master/helpers/kdocker.pod)) that the man page is built from ( using [kdocker_man.sh](https://github.com/user-none/KDocker/blob/master/helpers/kdocker_man.sh) )
4. Try hacking the **KDocker::printHelp()** function in [kdocker.cpp](https://github.com/user-none/KDocker/blob/a067154d77693718a7b04aa2aa03e19ce0ae1cb3/src/kdocker.cpp#L177)
5. Congratulate yourself on your progress :)
6. Consider moving to the next level by perusing [ketopt](https://attractivechaos.github.io/klib/#Ketopt%3A%20parsing%20command-line%20arguments)
7. Leave any other thoughts you have, here. I'm sure it'll help. Maybe others will contribute suggestions or even pull requests for your project.

**Comment by samuelznewton** [comment]
Okay, I might try some of this when I have some time!  This semester has been super busy so far though, so I don't know for sure when that might be.

**Comment by user-none** [comment]
This is added to v6.0 (not yet released).
