### ISSUE TITLE
How can I use the close button as a minimise button

### ISSUE THREAD

**Issue by CleanMachine1** [user-none/KDocker#86]
I have my kdocker running my application in the background, I always accidentally close it inside of minimise, is there a string of parameters I can give the command line within kdocker to stop/switch the close button?

Thanks in advance

**Comment by Daxx** [comment]
You can't.

https://github.com/user-none/KDocker/issues/15

**Comment by CleanMachine1** [comment]
Thats annoying but I will have to live with it, thanks for the really quick response
