### ISSUE TITLE
-l command questions

### ISSUE THREAD

**Issue by CleanMachine1** [user-none/KDocker#87]
Where does it store the startup?

I can't see it in crontab, autostart or systemctl. I need to know where the autostart lives or at least a way to disable autostarted programs

**Comment by Daxx** [comment]
?
KDocker doesn't attempt to autostart
What does kdocker do after it has started? (I assume it shows a + cursor)
What's your operating system? (& `kdocker -v`)

**Comment by CleanMachine1** [comment]
The man page clearly shows this       
> -l     Launch on startup

kdocker -v reports
> qt5ct: using qt5ct plugin
KDocker version: 5.0
Using Qt version: 5.12.8


Does this feature even work as it didn't work with terminal

**Comment by Daxx** [comment]
You must have found a very old man page.

When it was included, I think it applied to launching applications from a previous kdocker session at the same time kdocker is started. It never meant "Launch on system startup".

Here's a more recent one: https://www.mankier.com/1/kdocker
... or `kdocker -h` will show the options.

So,what is it you're trying to disable?

**Comment by CleanMachine1** [comment]
The version I have is available in the standard APT mint repo or ubuntu one#]b
I think the -l doesn't work actually since it doesn't seem to work, also I realised that I set up a autostart application with it.. which I named stupidly autostart... so I didn't see it.

All is solved, I guess.
Thanks for the help!
