### ISSUE TITLE
Sticky option doesn't work in Xfce

### ISSUE THREAD

**Issue by PoisonFrog** [user-none/KDocker#89]
KDocker only opens the application in the workspace it was minimized. The app kdocker was docking is a flatpak, I don't know if this can change something.

**Comment by illiakozey** [comment]
same problem

**Comment by Massimo-B** [comment]
2024 and still the same problem.

**Comment by Daxx** [comment]
> 2024 and still the same problem.

Be sure it's a KDocker problem before moaning. Have you reported it to [XFCE](https://gitlab.xfce.org/) where the problem seems to lie?

**Comment by Massimo-B** [comment]
Ok, I did not. Xfce has the feature "Always on visible workspace" which makes a window appear on all virtual desktops (workspaces in Xfce). I'm going to talk to the Xfce devs, why this is failing:
https://github.com/user-none/KDocker/blob/master/src/trayitem.cpp#L400
https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html

**Comment by user-none** [comment]
KDocker send a message to the WM requesting the window be treated sticky. There isn't anything KDocker can do if the WM isn't honoring the request.
