### ISSUE TITLE
Raise after minimized to system tray

### ISSUE THREAD

**Issue by niklas-st** [user-none/KDocker#90]
Simlar to #84. Starting Apps with kdocker works great, I use:
`kdocker -q -i /home/niklas/Pictures/Icons/spotify_icon.png spotify %U` for example.
Have been struggling with bringing windows back up from the system tray. I don't want to click.
Tried a modified version of this: https://pastebin.com/WXWU6xyL
Only problem was, that the Window ID was always wrong. There were two when doing:
`xdotool search spotify` and one brought up this tiny, buggy window which didnt show anything?
I've been bringing them up with xdotool windowmap.
This is my workaround for now: https://pastebin.com/T4gsNx9u

Maybe someone has a better suggestion?

**Comment by Daxx** [comment]
Useful feedback, thanks.

I thought Spotify has its own docking mechanism but apparently that's [changed](https://www.maketecheasier.com/minimize-spotify-to-system-tray-linux/)

If it works for you then that's the solution.
The most successful way of finding the window ID is usually with `wmctrl -l` but it won't show up for the windows that kdocker already has hidden. I keep meaning to look how it works but .... distractions.

**Comment by new-on-github32702** [comment]
Just for others facing the same problem:
My last script was pretty flawed because I used a specific Window ID.
Here is a new one: https://pastebin.com/U3YMKdVV
I think what happens is that the kdocked-app also counts as a window, which is why one has to use the second biggest number.

Hopefully this will be useful to some :)

**Comment by user-none** [comment]
KDocker 6.0 (future release) will support a DBus interface that will allow controlling behavior like this.
