### ISSUE TITLE
"Failed to grab mouse" Gnome Ubuntu 20.04

### ISSUE THREAD

**Issue by N-Accumbens** [user-none/KDocker#92]
I believe this is related to: 

1) [An old bug](https://bugzilla.redhat.com/show_bug.cgi?id=1300739)
2) [This recent listing](https://github.com/user-none/KDocker/issues/82)

On Ubuntu 20.04.2, DE: GNOME, when you press `Super`, type `kdocker` then try to run kdocker, it says "Failed to grab mouse". 

However, when you pin kdocker to the taskbar (Using the `Dash to panel` extension), you don't get the same issue

**Comment by Daxx** [comment]
I'm not familiar with that (KDE user here) but thanks for reporting.

[GNOME Dash to Panel Shell extension](https://extensions.gnome.org/extension/1160/dash-to-panel/
)

**Comment by varsvat** [comment]
Thanks @N-Accumbens !! I too am facing the same issue. Kdocker works after pinning to the taskbar

**Comment by FCollaPi** [comment]
Also having the same issue. It works when launching using `Alt+F2`.

However, attempting to use `Dock Another` from Kdocker menu also gives that error.

**Comment by ThalesCarl** [comment]
Same problem here on Zorin OS 15.3 and Gnome 3.30.2.

**Comment by user-none** [comment]
Can't reproduce on Ubuntu 24.04
