### ISSUE TITLE
Feature request: dock applications without window to system tray

### ISSUE THREAD

**Issue by Markus0000000** [user-none/KDocker#93]
To dock realy any application to system tray, it would be beautiful to dock apps without window or services to systray - only by using the PID. I have use ksystraycmd to dock apps like axel (cli download-manager) or minidlnad at their runtime in the systray, to have a reminder, that the app/service ist running. Since ksystraycmd is broken, I'm searching (like many people) for a replacement. KDocker could become that application!

**Comment by user-none** [comment]
KDocker is designed to work with applications that have windows.
