### ISSUE TITLE
Persisten Options and/or automatically open with Program

### ISSUE THREAD

**Issue by ReaderGuy42** [user-none/KDocker#94]
I use KDocker in connection with Thunderbird, since I can't Firetray/Birdtray to work right for me (Linux Mint 20.1). 

I do not need the setting "Balloon Title Changes", and was wondering if there was a way to have it remember that I unchecked that?

Another question is whether it was possible to have KDocker start automatically when I launch another program, i.e. in my case thunderbird?

Thanks :)

**Comment by Daxx** [comment]
KDocker 5.1 has persistent settings.

Q2) Yes. Change "thunderbird.desktop" and save it to "~/.local/share/applications/thunderbird.desktop" and it'll replace the entry in your app launcher, eventually.
`Exec=kdocker [options] thunderbird`

**Comment by ReaderGuy42** [comment]
> KDocker 5.1 has persistent settings.
> 

Does that mean the newer versions do not? Or am I doing something wrong.
Thanks!

**Comment by Daxx** [comment]
> > KDocker 5.1 has persistent settings.
> 
> Does that mean the newer versions do not? Or am I doing something wrong.
> Thanks!

5.1 and later.

There's a problem with the context menu not fully rendering the first time it appears (that's a Qt "optimization feature"). If you move the mouse pointer away and then back, it appears in full. Same with sub-menus.

**Comment by ReaderGuy42** [comment]
I don't understand that part, sorry. I am seeing the context menu, but it just resets every time I close the program.

**Comment by Daxx** [comment]
> I don't understand that part, sorry. I am seeing the context menu, but it just resets every time I close the program.

After unchecking "Balloon", save settings for thunderbird

![20210621_135951](https://user-images.githubusercontent.com/154675/122766205-2c4cec00-d299-11eb-8f3a-69d1c9bd0109.png)

**Comment by ReaderGuy42** [comment]
Ok, now I see, but I don't have that. The "Save settings" button is not there. I've moved the panel to make sure there wasn't anything hidden, and I've moved my mouse there and back several times and nothing happens.

**Comment by Daxx** [comment]
What does `kdocker -v` show?

Likely 5.0, in which case I suggest you compile a newer version yourself.or use the answer I gave for your other question.

**Comment by ReaderGuy42** [comment]
Yup, that was the issue. I had installed it through Mint's Software Manager which still has version 5.0. something.

If you don't mind answering another question, how do I install Qt? I think the link in the install readme file is dead.

**Comment by Daxx** [comment]
You don't need to install Qt, as such; all the packages you need are in the Mint repo (usually ending in "-dev" but I don't have a list of what they are.
Do the compile ... get the error ... search web for error message to see which Debian package resolves the error ... run "make" again ... get the next error ... repeat until the dragon is slain ;)

... or drop the error message here and I'll find it for you.

It'll be helpful if you make a note of the packages you install to help other users.
(I tend to have them installed already for other Qt software)

**Comment by ReaderGuy42** [comment]
Ok, so upon "qmake" I got the error that `qmake: could not exec '/usr/lib/qt5/bin/qmake': No such file or directory`. Then following [this person's comment](https://github.com/tetzank/qmenu_hud/issues/4) I ran `sudo apt install qt5-default`.
Then I tried qmake again and got "Project ERROR: Unknown module(s) in QT: x11extras". And now I don't know what to do haha

**Comment by Daxx** [comment]
libqt5x11extras5-dev

**Comment by ReaderGuy42** [comment]
Ok, cool, that made "qmake" work, but once I did "make" I got this:
`g++ -c -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DTRANSLATIONS_PATH=\"/usr/share/kdocker/i18n\" -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I3rdparty/qtsingleapplication/src -I. -Isrc -isystem /usr/include/X11 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o build/qtsingleapplication.o 3rdparty/qtsingleapplication/src/qtsingleapplication.cpp
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DTRANSLATIONS_PATH=\"/usr/share/kdocker/i18n\" -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I3rdparty/qtsingleapplication/src -I. -Isrc -isystem /usr/include/X11 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o build/qtlocalpeer.o 3rdparty/qtsingleapplication/src/qtlocalpeer.cpp
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DTRANSLATIONS_PATH=\"/usr/share/kdocker/i18n\" -DQT_NO_DEBUG -DQT_X11EXTRAS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I3rdparty/qtsingleapplication/src -I. -Isrc -isystem /usr/include/X11 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtX11Extras -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o build/application.o src/application.cpp
In file included from src/trayitem.h:37,
                 from src/trayitemmanager.h:31,
                 from src/kdocker.h:29,
                 from src/application.h:25,
                 from src/application.cpp:20:
src/xlibutil.h:33:10: fatal error: X11/Xlib-xcb.h: No such file or directory
   33 | #include <X11/Xlib-xcb.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:532: build/application.o] Error 1
`

**Comment by Daxx** [comment]
Three more ...
libxcb1-dev
libxpm-dev
libxmu-dev

(not sure if "libx11-xcb-dev" is needed; try those other three, first)

... nearly there ;)

**Comment by ReaderGuy42** [comment]
Ok, so I did have to install that last one, too. and then "make" worked, but then when I tried "make install" I got this

`ake install
/usr/lib/qt5/bin/qmake -install qinstall -exe kdocker /usr/bin/kdocker
Error copying kdocker to /usr/bin/kdocker: Cannot create /usr/bin/kdocker for output
make: [Makefile:610: install_target] Error 3 (ignored)
strip /usr/bin/kdocker
strip: '/usr/bin/kdocker': No such file
make: [Makefile:611: install_target] Error 1 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /opt/KDocker-5.3/resources/images/kdocker.png /usr/share/icons/hicolor/128x128/apps/kdocker.png
Error copying /opt/KDocker-5.3/resources/images/kdocker.png to /usr/share/icons/hicolor/128x128/apps/kdocker.png: Cannot create /usr/share/icons/hicolor/128x128/apps/kdocker.png for output
make: [Makefile:620: install_icons] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /opt/KDocker-5.3/helpers/appdata/kdocker.appdata.xml /usr/share/appdata/kdocker.appdata.xml
Error copying /opt/KDocker-5.3/helpers/appdata/kdocker.appdata.xml to /usr/share/appdata/kdocker.appdata.xml: Cannot create /usr/share/appdata/kdocker.appdata.xml for output
make: [Makefile:629: install_appdata] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /opt/KDocker-5.3/helpers/kdocker.desktop /usr/share/applications/kdocker.desktop
Error copying /opt/KDocker-5.3/helpers/kdocker.desktop to /usr/share/applications/kdocker.desktop: Cannot create /usr/share/applications/kdocker.desktop for output
make: [Makefile:638: install_desktop] Error 3 (ignored)
/usr/lib/qt5/bin/qmake -install qinstall /opt/KDocker-5.3/helpers/kdocker /etc/bash_completion.d/kdocker
Error copying /opt/KDocker-5.3/helpers/kdocker to /etc/bash_completion.d/kdocker: Cannot create /etc/bash_completion.d/kdocker for output
make: [Makefile:647: install_completion] Error 3 (ignored)`

Since it says that's optional, do I need to do that?
Also, sorry to be so much trouble, I'm still quite new to Linux, how easy is it to make a shortcut for this?

**Comment by Daxx** [comment]
**sudo** make install
Because you're installing to /usr
(You could run ./kdocker, without installing, from your build directly because it's already built -- therefore 'optional')

No trouble.

Shortcut for what? The install process?

**Comment by ReaderGuy42** [comment]
Yes!! Now it works :) No I meant shortcut e.g. for the desktop or the "start-menu" (is it still called that in Linux?)
In the start menu it's currently a blank that I can click for KDocker.

**Comment by Daxx** [comment]
The "[.desktop](https://specifications.freedesktop.org/desktop-entry-spec/latest/index.html#introduction)" is the near-equivalent of Win shortcut but far more flexible.
KDocker should be there, already because the [.desktop is in the installation](https://github.com/user-none/KDocker/blob/master/helpers/kdocker.desktop)

If you follow my answer to your Q2) above, for thunderbird, it'll appear in the "Start Menu" (launcher) ... perhaps not straight away.

Glad you got compiled. If you can close this issue, that'll be helpful. Thanks.

**Comment by ReaderGuy42** [comment]
Thank you!!
