### ISSUE TITLE
request: ability to pass posix signals on to the client application(s)

### ISSUE THREAD

**Issue by dreamcat4** [user-none/KDocker#96]
Situation:

* application `raysession` manages the opening and closing of other audio apps
* invokes from other application as `kdocker spotify`
* spotify app opens and gets minimized
* clearly `kdocker` knows and is managing spotify app
* want to close spotify, --> program `raysession` closes app by sending:
* `SIG-anything` to kdocker. Because spotify program was launched as `kdocker`

Desired outcome:

* `kdocker` accepts posix signal, but also passes it on to spotify app

Actual result:

* `spotify` app never received posix signal

Therefore spotify remains open, after being asked to close. And after `kdocker` itself has exited. There seems no options within kdocker to control this behaviour... It just needs to pass on the posix signal to the client. Being a spawned process that it had originally launched earlier on

**Comment by user-none** [comment]
This would break KDocker as it would be unable to receive signals intended for itself. All processes KDocker manages has their own PID and any signals need to be sent directly to the application itself. You need tow work with raysession to have it pass the signal to the Spotify process and not KDocker.

**Comment by dreamcat4** [comment]
nevermind - just discovered that it seems to work for SIGTERM
