### ISSUE TITLE
Provide option to relaunch in dock after closing (fake close to tray)

### ISSUE THREAD

**Issue by Ashark** [user-none/KDocker#97]
With apps that you want to trayify, it is very natural to use close button and expect the app to be continued working in tray. And I do it constantly. But of course, I am facing with the closed app, and I need to again open it and trayify.

This is already a feature request #15, and it was said
> Desired behaviour
When I click the 'close' button for a window, kdocker minimizes it and sends it to my system tray

and
> This was added in 4.3 but removed in 4.4 because it was unreliable and caused numerous issues.

While that feature request could still be opened waiting for solution, I have another idea for the solution, slightly more reliable.

We can watch if the app is still running. When user closes app, this is detected by watcher, and then we can launch it again minimized to tray. This way it feels like user closed it to tray.

Probably, it will not work for all cases (such as probably music apps?), that is why #15 is still a valid fr. But for my case it is totally ok. I need it for gtg (getting things gnome) application, and gnome apps is [known](https://github.com/getting-things-gnome/gtg/issues/548) to never receive tray functionality because of limitations of gnome.

I suggest adding new option for that. For example `-c  Relaunch docked when closing. Mimicking close to tray behavior.`.
And if user want to really close (stop restarting) the app, the close entry in tray menu can handle this.

**Comment by Ashark** [comment]
My temporary workaround for this is the following.

I edited the gtg application (right click in launcher menu, edit application) command  to following:
```bash
QT_QPA_PLATFORM=xcb GDK_BACKEND=x11 kdocker -m gtg; /home/andrew/bin/kdocker-fake-close-to-tray.sh gtg
```
In this command:
 -  kdocker and the app is launched using x11 backend. Needed under wayland, harmless if in x11. See [here](https://github.com/user-none/KDocker/issues/95#issuecomment-960779996) for more info.
 - the app window is visible (-m option) at launch
 - the watcher script (kdocker-fake-close-to-tray.sh) is launched (see below what it does).
 
 
Then created the /home/andrew/bin/kdocker-fake-close-to-tray.sh
```bash
#!/bin/bash
app_name="$1"

while true; do
    ps --no-headers -C "kdocker $app_name" -o args,state
    exit_code=$?
    if [[ $exit_code == 0 ]]; then
        echo "The app is running, sleeping 5 sec\n$(date)"
        sleep 5;
    else
        echo "The app was closed, relaunching minimized to tray"
        QT_QPA_PLATFORM=xcb GDK_BACKEND=x11 kdocker "$app_name" &
        sleep 10 # just to be safe, because there is a delay after launching.
    fi
done
```
As you can see, in the launch command `kdocker "$app_name"` there is no more -m option, so it will be initially trayed (to be precise, the app window is visible for a second, but this is another issue, probably could be solved by applying "minimized - apply initially" in window rules). 

Result:
You launch app from start menu, its window is initially visible. You close the app with close button. You see that app is "still" in tray.

If you want to stop relaunching it, open task manager (ctrl + esc) and kill the fake close to tray process.

**Comment by user-none** [comment]
There are going to be too many issues try to reopen applications. It will be very confusing to people and I can't see many people wanting to use it.
